### ISSUE TITLE
Node-gyp / Node 0.12 error

### ISSUE THREAD

**Issue by stockholmux** [ncb000gt/node.bcrypt.js#277]
Hi,

I'm getting the following error when trying to install a package that depends on bcrypt (passwordless) with NPM.

```
20 errors generated.
make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/globen/nodeSites/haloid/node_modules/passwordless-redisstore/node_modules/bcrypt
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.6.0
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.7.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.7.8 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/globen/nodeSites/haloid/npm-debug.log
```

If I switch back to Node 0.10 with nvm, the install succeeds. Am I doing something wrong with 0.12?

**Comment by lomteslie** [comment]
Same issue here. bcrypt is choking on the Node 0.12.

**Comment by defunctzombie** [comment]
Travis is testing 0.12 for us and it seems to work there. Likely some other issue. The log here is not helpful enough as it doesn't say why make failed.

**Comment by ScOut3R** [comment]
Running node 0.12 on FreeBSD 8.4 I'm having the following issue. Maybe it's helpful.

```
> bcrypt@0.7.8 install ./node_modules/bcrypt
> node-gyp rebuild

gmake: Entering directory './node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
../src/bcrypt_node.cc: In destructor 'virtual<unnamed>::baton_base::~baton_base()':
../src/bcrypt_node.cc:54: error: 'class v8::Persistent<v8::Function, v8::NonCopyablePersistentTraits<v8::Function> >' has no member named 'Dispose'
../src/bcrypt_node.cc: At global scope:
../src/bcrypt_node.cc:128: error: variable or field 'GenSaltAsync' declared void
../src/bcrypt_node.cc:128: error: 'uv_work_t' was not declared in this scope
../src/bcrypt_node.cc:128: error: 'req' was not declared in this scope
../src/bcrypt_node.cc:137: error: variable or field 'GenSaltAsyncAfter' declared void
../src/bcrypt_node.cc:137: error: 'uv_work_t' was not declared in this scope
../src/bcrypt_node.cc:137: error: 'req' was not declared in this scope
../src/bcrypt_node.cc:429: error: expected `}' at end of input
bcrypt_lib.target.mk:86: recipe for target 'Release/obj.target/bcrypt_lib/src/bcrypt_node.o' failed
gmake: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
```
