### ISSUE TITLE
404 status code downloading tarball

### ISSUE THREAD

**Issue by knownasilya** [ncb000gt/node.bcrypt.js#287]
```no-highlight
bcrypt@0.8.2 install /Users/iradchenko/workspace/nycbb/node_modules/bcrypt
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:246:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:166:7)
gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1176:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:166:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:410:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:300:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/iradchenko/workspace/nycbb/node_modules/bcrypt
gyp ERR! node -v v1.5.1
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "bcrypt" "--save"
npm ERR! node v1.5.1
npm ERR! npm  v2.6.1
npm ERR! code ELIFECYCLE
```

**Comment by ncb000gt** [comment]
This isn't a bcrypt module issue.

You might find some better info following: https://github.com/ncb000gt/node.bcrypt.js/issues/268#issuecomment-73248303

**Comment by knownasilya** [comment]
@ncb000gt thanks!

**Comment by patbaker82** [comment]
@knownasilya It looks like you're using io.js.  The io.js ships with patched npm.  If you update npm, IE `npm install npm -g` it will overwrite the npm changes and will cause this error.

**Comment by knownasilya** [comment]
@patbaker82 thank you, I was looking everywhere on how to get the updated npm..
