### ISSUE TITLE
bcrypt error

### ISSUE THREAD

**Issue by George02** [ncb000gt/node.bcrypt.js#289]
Error: /home/george/Desktop/myProject/node_modules/bcrypt/build/Release/bcrypt_lib.node: undefined symbol: node_module_register
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)
        at bindings     (/home/george/Desktop/myProject/node_modules/bcrypt/node_modules/bindings/bindings.js:76:44)
        at Object.<anonymous> (/home/george/Desktop/myProject/node_modules/bcrypt/bcrypt.js:3:35)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)

What would be the causes for this error ?

Operating system: Linux Mint 17.1
gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) 
Python 2.7.6
node-gyp@1.0.3

**Comment by lovell** [comment]
http://stackoverflow.com/questions/29495599/bcrypt-lib-node-undefined-symbol-node-module-register
