### ISSUE TITLE
node-gyp error in bcrypt package

### ISSUE THREAD

**Issue by diegoddox** [ncb000gt/node.bcrypt.js#291]
Can someone help me with this issue, I'm trying to run npm install --save bcrypt on my ubuntu and I get this error.

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v0.12.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.13.0-43-generic
gyp ERR! command "node" "/root/.nvm/versions/node/v0.12.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/www/jlovesyou-server/node_modules/bcrypt
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Linux 3.13.0-43-generic
npm ERR! argv "/root/.nvm/versions/node/v0.12.2/bin/node" "/root/.nvm/versions/node/v0.12.2/bin/npm" "install" "bcrypt"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.8.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/www/jlovesyou-server/npm-debug.log

**Comment by diegoddox** [comment]
I find the solution here.
http://stackoverflow.com/questions/29103839/impossible-to-install-bcrypt-with-npm-on-ec2
