### ISSUE TITLE
Can't install on Mac OS X 10.10.2

### ISSUE THREAD

**Issue by peek4y** [ncb000gt/node.bcrypt.js#293]
I tried installing bcrypt and here are the logs

npm http GET https://registry.npmjs.org/bcrypt
npm http 304 https://registry.npmjs.org/bcrypt
npm http GET https://registry.npmjs.org/bindings/1.2.0
npm http GET https://registry.npmjs.org/nan/1.7.0
npm http 304 https://registry.npmjs.org/nan/1.7.0
npm http 304 https://registry.npmjs.org/bindings/1.2.0
npm http GET https://registry.npmjs.org/bindings/-/bindings-1.2.0.tgz
npm http 200 https://registry.npmjs.org/bindings/-/bindings-1.2.0.tgz

> bcrypt@0.8.2 install /Users/gautham/Work/omega.core/node_modules/bcrypt
> node-gyp rebuild

  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
In file included from ../src/bcrypt_node.cc:1:
../node_modules/nan/nan.h:68:13: error: no type named 'UnboundScript' in
      namespace 'v8'
typedef v8::UnboundScript      NanUnboundScript;
        ~~~~^
In file included from ../src/bcrypt_node.cc:1:
In file included from ../node_modules/nan/nan.h:80:
../node_modules/nan/nan_new.h:182:20: error: no member named 'UnboundScript' in
      namespace 'v8'
struct Factory<v8::UnboundScript> : FactoryBase<v8::UnboundScript> {
               ~~~~^
In file included from ../src/bcrypt_node.cc:1:
In file included from ../node_modules/nan/nan.h:80:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:29:25: error: cannot initialize
      a parameter of type 'int' with an rvalue of type 'v8::Isolate *'
  return v8::Array::New(v8::Isolate::GetCurrent());
                        ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/gautham/.node-gyp/0.11.4/deps/v8/include/v8.h:2320:31: note: passing
      argument to parameter 'length' here
  static Local<Array> New(int length = 0);
                              ^
In file included from ../src/bcrypt_node.cc:1:
In file included from ../node_modules/nan/nan.h:80:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:34:52: error: too many arguments
      to function call, expected at most single argument 'length', have 2
      arguments
  return v8::Array::New(v8::Isolate::GetCurrent(), length);
         ~~~~~~~~~~~~~~                            ^~~~~~
/Users/gautham/.node-gyp/0.11.4/deps/v8/include/v8.h:2320:3: note: 'New'
      declared here
  static Local<Array> New(int length = 0);
  ^
In file included from ../src/bcrypt_node.cc:1:
In file included from ../node_modules/nan/nan.h:80:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:41:54: error: too many arguments
      to function call, expected single argument 'value', have 2 arguments
  return v8::Boolean::New(v8::Isolate::GetCurrent(), value);
         ~~~~~~~~~~~~~~~~                            ^~~~~
/Users/gautham/.node-gyp/0.11.4/deps/v8/include/v8.h:5964:1: note: 'New'
      declared here
Handle<Boolean> Boolean::New(bool value) {
^
In file included from ../src/bcrypt_node.cc:1:
In file included from ../node_modules/nan/nan.h:80:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:64:51: error: too many arguments
      to function call, expected single argument 'time', have 2 arguments
  return v8::Date::New(v8::Isolate::GetCurrent(), value).As<v8::Date>();
         ~~~~~~~~~~~~~                            ^~~~~
/Users/gautham/.node-gyp/0.11.4/deps/v8/include/v8.h:2710:3: note: 'New'
      declared here
  static Local<Value> New(double time);
  ^
In file included from ../src/bcrypt_node.cc:1:
In file included from ../node_modules/nan/nan.h:80:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:64:69: error: expected '(' for
      function-style cast or type construction
  return v8::Date::New(v8::Isolate::GetCurrent(), value).As<v8::Date>();
                                                            ~~~~~~~~^
../node_modules/nan/nan_implementation_12_inl.h:64:71: error: expected
      expression
  return v8::Date::New(v8::Isolate::GetCurrent(), value).As<v8::Date>();
                                                                      ^
../node_modules/nan/nan_implementation_12_inl.h:71:55: error: too many arguments
      to function call, expected single argument 'value', have 2 arguments
  return v8::External::New(v8::Isolate::GetCurrent(), value);
         ~~~~~~~~~~~~~~~~~                            ^~~~~
/Users/gautham/.node-gyp/0.11.4/deps/v8/include/v8.h:2869:3: note: 'New'
      declared here
  static Local<External> New(void* value);
  ^
In file included from ../src/bcrypt_node.cc:1:
In file included from ../node_modules/nan/nan.h:80:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:79:29: error: too many arguments
      to function call, expected 0, have 3
  return v8::Function::New( v8::Isolate::GetCurrent()
         ~~~~~~~~~~~~~~~~~  ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/gautham/.node-gyp/0.11.4/deps/v8/include/v8.h:2292:3: note: 'New'
      declared here
  static Local<Object> New();
  ^
In file included from ../src/bcrypt_node.cc:1:
In file included from ../node_modules/nan/nan.h:80:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:90:10: error: no matching
      function for call to 'New'
  return v8::FunctionTemplate::New( v8::Isolate::GetCurrent()
         ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/gautham/.node-gyp/0.11.4/deps/v8/include/v8.h:3263:48: note: candidate
      function not viable: no known conversion from 'v8::Isolate *' to
      'InvocationCallback' (aka 'Handle<v8::Value> (*)(const v8::Arguments &)')
      for 1st argument
  V8_DEPRECATED(static Local<FunctionTemplate> New(
                                               ^
/Users/gautham/.node-gyp/0.11.4/deps/v8/include/v8.h:88:35: note: expanded from
      macro 'V8_DEPRECATED'
#define V8_DEPRECATED(declarator) declarator __attribute__ ((deprecated))
                                  ^
/Users/gautham/.node-gyp/0.11.4/deps/v8/include/v8.h:3268:34: note: candidate
      function not viable: no known conversion from 'v8::Isolate *' to
      'FunctionCallback' (aka 'void (*)(const FunctionCallbackInfo<v8::Value>
      &)') for 1st argument
  static Local<FunctionTemplate> New(
                                 ^
In file included from ../src/bcrypt_node.cc:1:
In file included from ../node_modules/nan/nan.h:80:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:108:33: error: too many
      arguments to function call, expected single argument 'value', have 2
      arguments
                              , value).As<v8::NumberObject>();
                                ^~~~~
/Users/gautham/.node-gyp/0.11.4/deps/v8/include/v8.h:2744:3: note: 'New'
      declared here
  static Local<Value> New(double value);
  ^
In file included from ../src/bcrypt_node.cc:1:
In file included from ../node_modules/nan/nan.h:80:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:108:59: error: expected '(' for
      function-style cast or type construction
                              , value).As<v8::NumberObject>();
                                          ~~~~~~~~~~~~~~~~^
../node_modules/nan/nan_implementation_12_inl.h:108:61: error: expected
      expression
                              , value).As<v8::NumberObject>();
                                                            ^
../node_modules/nan/nan_implementation_12_inl.h:128:7: error: no matching
      function for call to 'NewFromUnsigned'
      v8::Uint32::NewFromUnsigned(v8::Isolate::GetCurrent(), value));
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/gautham/.node-gyp/0.11.4/deps/v8/include/v8.h:1939:25: note: candidate
      function not viable: no known conversion from 'v8::Isolate *' to
      'uint32_t' (aka 'unsigned int') for 1st argument
  static Local<Integer> NewFromUnsigned(uint32_t value, Isolate*);
                        ^
/Users/gautham/.node-gyp/0.11.4/deps/v8/include/v8.h:1937:25: note: candidate
      function not viable: requires single argument 'value', but 2 arguments
      were provided
  static Local<Integer> NewFromUnsigned(uint32_t value);
                        ^
In file included from ../src/bcrypt_node.cc:1:
In file included from ../node_modules/nan/nan.h:80:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:134:7: error: no matching
      function for call to 'NewFromUnsigned'
      v8::Uint32::NewFromUnsigned(v8::Isolate::GetCurrent(), value));
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/gautham/.node-gyp/0.11.4/deps/v8/include/v8.h:1939:25: note: candidate
      function not viable: no known conversion from 'v8::Isolate *' to
      'uint32_t' (aka 'unsigned int') for 1st argument
  static Local<Integer> NewFromUnsigned(uint32_t value, Isolate*);
                        ^
/Users/gautham/.node-gyp/0.11.4/deps/v8/include/v8.h:1937:25: note: candidate
      function not viable: requires single argument 'value', but 2 arguments
      were provided
  static Local<Integer> NewFromUnsigned(uint32_t value);
                        ^
In file included from ../src/bcrypt_node.cc:1:
In file included from ../node_modules/nan/nan.h:80:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:141:26: error: too many
      arguments to function call, expected 0, have 1
  return v8::Object::New(v8::Isolate::GetCurrent());
         ~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/gautham/.node-gyp/0.11.4/deps/v8/include/v8.h:2292:3: note: 'New'
      declared here
  static Local<Object> New();
  ^
In file included from ../src/bcrypt_node.cc:1:
In file included from ../node_modules/nan/nan.h:80:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:148:10: error: no matching
      function for call to 'New'
  return v8::ObjectTemplate::New(v8::Isolate::GetCurrent());
         ^~~~~~~~~~~~~~~~~~~~~~~
/Users/gautham/.node-gyp/0.11.4/deps/v8/include/v8.h:3528:32: note: candidate
      function not viable: no known conversion from 'v8::Isolate *' to
      'Handle<v8::FunctionTemplate>' for 1st argument
  static Local<ObjectTemplate> New(Handle<FunctionTemplate> constructor);
                               ^
/Users/gautham/.node-gyp/0.11.4/deps/v8/include/v8.h:3354:32: note: candidate
      function not viable: requires 0 arguments, but 1 was provided
  static Local<ObjectTemplate> New();
                               ^
In file included from ../src/bcrypt_node.cc:1:
In file included from ../node_modules/nan/nan.h:80:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:164:7: error: no member named
      'ScriptCompiler' in namespace 'v8'
  v8::ScriptCompiler::Source src(source);
  ~~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:103:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/gautham/Work/omega.core/node_modules/bcrypt
gyp ERR! node -v v0.11.4
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok 
npm ERR! weird error 1
npm ERR! not ok code 0

**Comment by ncb000gt** [comment]
The errors you're seeing here are for the nan project. You might want to take a look over there to make sure you have any dependencies for it.

**Comment by JuanchiSan** [comment]
I had exactly the same issue.

**Comment by adityabansod** [comment]
I rolled back to using bcrypt `0.8.0` which worked.

**Comment by cstigler** [comment]
Just to add to this, had the same issues and rolling back to 0.8.0 worked for me also.

**Comment by peek4y** [comment]
Yeah, rolled back to 0.8.0, works fine.

**Comment by jerryharrison** [comment]
Similar issue here too, rolling back to 0.8.0 helped!
