### ISSUE TITLE
iojs 2.0.0 cant build

### ISSUE THREAD

**Issue by willin** [ncb000gt/node.bcrypt.js#302]
```
/Users/willin/Documents/temp/nodeclub/node_modules/bcrypt/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: Module version mismatch. Expected 44, got 43.
  at Error (native)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Module.require (module.js:366:17)
  at require (module.js:385:17)
  at bindings (/Users/willin/Documents/temp/nodeclub/node_modules/bcrypt/node_modules/bindings/bindings.js:76:44)
  at Object.<anonymous> (/Users/willin/Documents/temp/nodeclub/node_modules/bcrypt/bcrypt.js:3:35)
  at Module._compile (module.js:431:26)
  at Object.Module._extensions..js (module.js:449:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Module.require (module.js:366:17)
  at require (module.js:385:17)
  at Object.<anonymous> (/Users/willin/Documents/temp/nodeclub/common/tools.js:2:14)
  at Module._compile (module.js:431:26)
  at Object.Module._extensions..js (module.js:449:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Module.require (module.js:366:17)
  at require (module.js:385:17)
  at Object.<anonymous> (/Users/willin/Documents/temp/nodeclub/proxy/reply.js:5:13)
  at Module._compile (module.js:431:26)
  at Object.Module._extensions..js (module.js:449:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Module.require (module.js:366:17)
  at require (module.js:385:17)
  at Object.<anonymous> (/Users/willin/Documents/temp/nodeclub/proxy/topic.js:6:13)
  at Module._compile (module.js:431:26)
  at Object.Module._extensions..js (module.js:449:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Module.require (module.js:366:17)
  at require (module.js:385:17)
  at Object.<anonymous> (/Users/willin/Documents/temp/nodeclub/proxy/message.js:6:13)
  at Module._compile (module.js:431:26)
  at Object.Module._extensions..js (module.js:449:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Module.require (module.js:366:17)
  at require (module.js:385:17)
  at Object.<anonymous> (/Users/willin/Documents/temp/nodeclub/proxy/index.js:2:19)
  at Module._compile (module.js:431:26)
  at Object.Module._extensions..js (module.js:449:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Module.require (module.js:366:17)
  at require (module.js:385:17)
  at Object.<anonymous> (/Users/willin/Documents/temp/nodeclub/controllers/sign.js:5:12)
  at Module._compile (module.js:431:26)
  at Object.Module._extensions..js (module.js:449:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Module.require (module.js:366:17)
  at require (module.js:385:17)
  at Object.<anonymous> (/Users/willin/Documents/temp/nodeclub/web_router.js:12:12)
  at Module._compile (module.js:431:26)
  at Object.Module._extensions..js (module.js:449:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Module.require (module.js:366:17)
  at require (module.js:385:17)
  at Object.<anonymous> (/Users/willin/Documents/temp/nodeclub/app.js:23:17)
  at Module._compile (module.js:431:26)
  at Object.Module._extensions..js (module.js:449:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Function.Module.runMain (module.js:472:10)
  at startup (node.js:124:18)
  at node.js:959:3
```

**Comment by airyland** [comment]
+1

**Comment by defunctzombie** [comment]
Make sure you are on the latest version of bcrypt.

**Comment by airyland** [comment]
the latest build of bcrypt on iojs failed too.

https://travis-ci.org/ncb000gt/node.bcrypt.js/jobs/61515709

![image](https://cloud.githubusercontent.com/assets/559179/7509549/ae89ec0e-f4c4-11e4-88c7-80bce25226cf.png)

**Comment by defunctzombie** [comment]
I think that is just some travis download issue.

**Comment by willin** [comment]
is tested?

**Comment by defunctzombie** [comment]
I believe so. You can search existing issues on the topic: https://github.com/ncb000gt/node.bcrypt.js/pull/300

**Comment by chrisveness** [comment]
I am having similar (same?) problem with io.js v2.0.0 / v2.0.1 (iojs-v1.8.1 is fine).

Everything seems fine in the browser, but using `npm test` (co-supertest), I see the following errors:

~~~~
[Error: Module did not self-register.]
js-bson: Failed to load c++ bson extension, using pure JS version
~~~~

~~~~
  Error: Module version mismatch. Expected 44, got 43.
      at Error (native)
      at Module.load (module.js:356:32)
      at Function.Module._load (module.js:311:12)
      at Module.require (module.js:366:17)
      at require (module.js:385:17)
      at bindings (/.../node_modules/co-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:76:44)
      at Object.<anonymous> (/.../node_modules/co-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
      at Module._compile (module.js:431:26)
      at Object.Module._extensions..js (module.js:449:10)
      at Module.load (module.js:356:32)
      at Function.Module._load (module.js:311:12)
      at Module.require (module.js:366:17)
      at require (module.js:385:17)
      at Object.<anonymous> (/.../node_modules/co-bcrypt/index.js:1:76)
      at Module._compile (module.js:431:26)
      at Object.Module._extensions..js (module.js:449:10)
      at Module.load (module.js:356:32)
      at Function.Module._load (module.js:311:12)
      at Module.require (module.js:366:17)
      at require (module.js:385:17)
      at Object.<anonymous> (/.../apps/admin/passport.js:14:21)
      at Module._compile (module.js:431:26)
      at Object.Module._extensions..js (module.js:449:10)
      at Module.load (module.js:356:32)
      at Function.Module._load (module.js:311:12)
      at Module.require (module.js:366:17)
      at require (module.js:385:17)
      at Object.<anonymous> (/.../apps/admin/app-admin.js:27:1)
      at Module._compile (module.js:431:26)
      at Object.Module._extensions..js (module.js:449:10)
      at Module.load (module.js:356:32)
      at Function.Module._load (module.js:311:12)
      at Module.require (module.js:366:17)
      at require (module.js:385:17)
      at Object.subApp (/.../app.js:78:37)
      at GeneratorFunctionPrototype.next (native)
      at onFulfilled (/.../node_modules/co/index.js:64:19)
      at /.../node_modules/co/index.js:53:5
      at Object.co (/.../node_modules/co/index.js:49:10)
      at Object.toPromise (/.../node_modules/co/index.js:117:63)
      at next (/.../node_modules/co/index.js:98:29)
      at onFulfilled (/.../node_modules/co/index.js:68:7)
      at /.../node_modules/co/index.js:53:5
      at Object.co (/.../node_modules/co/index.js:49:10)
      at Object.toPromise (/.../node_modules/co/index.js:117:63)
      at next (/.../node_modules/co/index.js:98:29)
      at onFulfilled (/.../node_modules/co/index.js:68:7)
~~~~

Everything seems up to date – `npm ls bcrypt bindings nan` gives:

~~~~
├─┬ bunyan@1.3.5
│ └─┬ dtrace-provider@0.4.0
│   └── nan@1.5.3 
├─┬ co-bcrypt@1.0.0
│ └─┬ bcrypt@0.8.3 
│   ├── bindings@1.2.1 
│   └── nan@1.8.4 
└─┬ monk@1.0.1
  └─┬ mongodb@1.4.35
    ├─┬ bson@0.2.21
    │ └── nan@1.7.0 
    └─┬ kerberos@0.0.9
      └── nan@1.6.2 
~~~~

This is a bit beyond me: I don't know if the issue is with bcrypt, io.js, or somewhere else...

**Comment by tychotatitscheff** [comment]
Houston we have a problem : https://travis-ci.org/ncb000gt/node.bcrypt.js/builds
Can you please reopen this since it's definitivly not building on iojs 2.x.x (and on 1.8.x but did'nt test all version of iojs to find whan it started to fail).

**Comment by mattapperson** [comment]
+1 this needs to be reopened

**Comment by defunctzombie** [comment]
I have tested this on my mac with iojs 2.0.2 and latest bcrypt and it works. I am locking this issue. If you have a problem it should be a new issue with a DETAILED description of your specific issue and what you have done to debug it and fix it.
