### ISSUE TITLE
Error to install bcrypt via npm

### ISSUE THREAD

**Issue by mrcmrc** [ncb000gt/node.bcrypt.js#304]
Hello, e have a error to install bcrypt via npm:
```
npm WARN package.json trimtrim@0.0.1 No repository field.
npm WARN package.json trimtrim@0.0.1 No README data
npm http GET https://registry.npmjs.org/bcrypt
npm http 304 https://registry.npmjs.org/bcrypt
npm http GET https://registry.npmjs.org/bindings/1.2.1
npm http GET https://registry.npmjs.org/nan/1.8.4
npm http 304 https://registry.npmjs.org/nan/1.8.4
npm http 304 https://registry.npmjs.org/bindings/1.2.1
 
> bcrypt@0.8.3 install /home/rocketcode/trimtrim/node_modules/bcrypt
> node-gyp rebuild
 
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:43:28)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:46:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:57:16
gyp ERR! stack     at Object.oncomplete (fs.js:107:15)
gyp ERR! System Linux 3.13.0-29-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/rocketcode/trimtrim/node_modules/bcrypt
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm ERR! bcrypt@0.8.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.8.3 install script.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.
 
npm ERR! System Linux 3.13.0-29-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "bcrypt"
npm ERR! cwd /home/rocketcode/trimtrim
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/rocketcode/trimtrim/npm-debug.log
npm ERR! not ok code 0

```
What is this?
======

**Comment by tonytamps** [comment]
```
gyp ERR! build error 
gyp ERR! stack Error: not found: make
```

You need to install your distribution's `make` package.
something like `sudo apt-get install make`
