### ISSUE TITLE
NVM, node-gyp and bcrypt with Node v0.12.3

### ISSUE THREAD

**Issue by lanceschi** [ncb000gt/node.bcrypt.js#308]
Hi,

on a spare VPS (ubuntu linux x86_64) I a have system install of Node v0.10.33. Recently I installed [NVM](https://github.com/creationix/nvm) and Node v0.12.3 to test a webapp with the latest stable Node. I kept the system Node v0.10.33 installation. I emptied the `cwd/node_modules/` folder, I switched to Node v0.12.3 (`$ nvm use 0.12.3`) and then finally I execute `$ sudo npm install`.

After that whenever I launched the Express app I encounterd an issue with the bcrypt npm module. It seems related to module compiling/building. Here's the log anyway:

```bash
Starting background Express server
/home/lanceschi/node/showcase/node_modules/bcrypt/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/home/lanceschi/node/showcase/node_modules/bcrypt/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/lanceschi/node/showcase/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/lanceschi/node/showcase/server/routes/sessions.js:2:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/lanceschi/node/showcase/server/app.js:49:1)
    at Module._compile (module.js:460:26)
Stopping Express server
```

I checked `cwd/node_modules/bcrypt/build/config.gypi` and I saw many references to system node v0.10.3, even though I execute the sudo npm install after switching to Node v0.12.3 (and double checking it). Here's the steps I followed to bypass the issue:

1. Install node-gyp globally with current node v0.12.3 (`$ sudo npm install node-gyp -g`)
2. Go to bcrypt root folder `$ cd cwd/node_modules/bcrypt/`
3. Execute `$ node-gyp configure`
4. Execute `$ node-gyp build`

Now everything works just fine. Is there a workaround to this behaviour or am I missing some step in NVM installation/configuration in order to make it fully compatible with bcrypt/node-gyp building/installation?

Thanks and BTW great module!

**Comment by nick-ma** [comment]
I've met the same problem.
When I upgrade nodejs to 0.12.3 on my Mac Book Pro, bcrypt out of functions. Then I tried to npm install bcrypt, node-gyp ended up with error. At the same time, npm removed all staffs in bcrypt folder.
I've tried many times, and finally give it up and back to node 0.10.26. 
In node 0.10.26, npm install bcrypt ends with success.

**Comment by g2graman** [comment]
Try updating node-gyp globally with:

    sudo npm install -g node-gyp

**Comment by lanceschi** [comment]
@nick-ma weird! Bcrypt is working for me with node v0.12.3, altough automatic module installation fails recognizing nvm node v0.12.3 and goes with system install node v0.10.3.

@g2graman that's what I did and reported. After my  comment I even uninstalled bcrypt and reinstalled it via command line. Same result. I had to bypass the issue with the aforementioned manual procedure.

**Comment by defunctzombie** [comment]
Sounds like an issue with your env, node-gyp or something else that is not this module

**Comment by RobKohr** [comment]
I had this problem too. I had node-v0.10.something installed and and bcrypt 0.8.3 installed and working fine. I upgraded node to 0.12.7 and started getting the same error as you. 

I uninstalled bcrypt and reinstalled it, and then all was good.
