### ISSUE TITLE
Failed to compile bcrypt for Node 2.3.1 (Electron run-time environment)

### ISSUE THREAD

**Issue by s-a** [ncb000gt/node.bcrypt.js#323]
``` bash
[7388:0809/065529:INFO:CONSOLE(0)] recompiling native modules in C:\git\require processor: ia32 electron: 0.30.3 v8: 4.3.61.21
[7388:0809/065529:INFO:CONSOLE(0)] compile bcrypt
[7388:0809/065529:INFO:CONSOLE(0)] rd /S /Q C:\Users\Stephan\AppData\Roaming\npm\node_modules\iron-node\node_modules\electron-recompile\tmp\bcrypt@0.8.4
[7388:0809/065530:INFO:CONSOLE(0)] git clone --depth=1 https://github.com/ncb000gt/node.bcrypt.js.git C:\Users\Stephan\AppData\Roaming\npm\node_modules\iron-node\node_modules\electron-recompile\tmp\bcrypt@0.8.4
[7388:0809/065532:INFO:CONSOLE(0)] cd C:\Users\Stephan\AppData\Roaming\npm\node_modules\iron-node\node_modules\electron-recompile\tmp\bcrypt@0.8.4 && set HOME=electron-gyp && node-gyp rebuild --target=0.30.3 --arch=ia32 --dist-url=https://atom.io/download/atom-shell
[7388:0809/065554:INFO:CONSOLE(0)] Failed to compile : bcrypt
[7388:0809/065554:INFO:CONSOLE(0)] Error: Command failed: cd C:\Users\Stephan\AppData\Roaming\npm\node_modules\iron-node\node_modules\electron-recompile\tmp\bcrypt@0.8.4 && set HOME=electron-gyp && node-gyp rebuild --target=0.30.3 --arch=ia32 --dist-url=https://atom.io/download/atom-shell
gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.2
gyp info using node@0.12.6 | win32 | ia32
gyp http GET https://atom.io/download/atom-shell/v0.30.3/node-v0.30.3.tar.gz
gyp http 200 https://atom.io/download/atom-shell/v0.30.3/node-v0.30.3.tar.gz
gyp http GET https://atom.io/download/atom-shell/v0.30.3/SHASUMS256.txt
gyp http GET https://atom.io/download/atom-shell/v0.30.3/x64/node.lib
gyp http GET https://atom.io/download/atom-shell/v0.30.3/node.lib
gyp http 200 https://atom.io/download/atom-shell/v0.30.3/SHASUMS256.txt
gyp http 200 https://atom.io/download/atom-shell/v0.30.3/node.lib
gyp http 200 https://atom.io/download/atom-shell/v0.30.3/x64/node.lib
gyp info spawn c:\python27\python.exe
gyp info spawn args [ 'C:\\Users\\Stephan\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Stephan\\AppData\\Roaming\\npm\\node_modules\\iron-node\\node_modules\\electron-recompile\\tmp\\bcrypt@0.8.4\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Stephan\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Stephan\\AppData\\Roaming\\npm\\node_modules\\iron-node\\node_modules\\electron-recompile\\tmp\\bcrypt@0.8.4\\electron-gyp \\.node-gyp\\0.30.3\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
```

Unfortunately electron console eats some logs so this is what i get if want to install with node 0.12.6
```bash
module.js:338
    throw err;
          ^
Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at [eval]:1:1
    at Object.exports.runInThisContext (vm.js:74:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:460:26)
    at evalScript (node.js:431:25)
    at startup (node.js:90:7)
gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Stephan\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:357:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Users\\Stephan\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=0.30.3" "--arch=ia32" "--dist-url=https://atom.io/download/atom-shell"
gyp ERR! cwd C:\Users\Stephan\AppData\Roaming\npm\node_modules\iron-node\node_modules\electron-recompile\tmp\bcrypt@0.8.4
gyp ERR! node -v v0.12.6
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
```

ref:
 - https://github.com/nodejs/io.js/issues/1620
 - https://github.com/s-a/iron-node/issues/44

**Comment by defunctzombie** [comment]
Seems like a problem with your build environment. This module works on iojs 2.x and nan is specified in package.json dependencies. I suggest doing some more debugging.
