### ISSUE TITLE
CentOS 6.6 can't compile 0.8.5

### ISSUE THREAD

**Issue by Calpicow** [ncb000gt/node.bcrypt.js#326]
```
make: Entering directory `/tmp/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
In file included from ../src/bcrypt_node.cc:1:
../node_modules/nan/nan.h:318: error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’
make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
make: Leaving directory `/tmp/node_modules/bcrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 2.6.32-504.3.3.el6.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/node_modules/bcrypt
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok 
npm ERR! weird error 1
npm ERR! not ok code 0
```

**Comment by defunctzombie** [comment]
`../node_modules/nan/nan.h:318: error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’` this is an error in the nan project. Please report it there.

**Comment by Calpicow** [comment]
Installing `nan@2.0.5` by itself works fine.

**Comment by rmoetwil** [comment]
See https://github.com/nodejs/nan/issues/414.
If you upgrade node-gyp you should be fine

**Comment by edu2004eu** [comment]
@rmoetwil your answer fixed the issue. Thanks.
