### ISSUE TITLE
node-gyp rebuild fails on beanstalk

### ISSUE THREAD

**Issue by mcassagnes** [ncb000gt/node.bcrypt.js#331]
About 75% of the deploys on Beanstalk fail with this error log:

```
21071 verbose unlock done using /tmp/.npm/_locks/im-resize-5b3ee60e1151f399.lock for /tmp/deployment/application/node_modules/im-resize
21072 verbose stack Error: bcrypt@0.8.5 install: `node-gyp rebuild`
21072 verbose stack Exit status 1
21072 verbose stack     at EventEmitter.<anonymous> (/opt/elasticbeanstalk/node-install/node-v0.12.6-linux-x64/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
21072 verbose stack     at EventEmitter.emit (events.js:110:17)
21072 verbose stack     at ChildProcess.<anonymous> (/opt/elasticbeanstalk/node-install/node-v0.12.6-linux-x64/lib/node_modules/npm/lib/utils/spawn.js:24:14)
21072 verbose stack     at ChildProcess.emit (events.js:110:17)
21072 verbose stack     at maybeClose (child_process.js:1015:16)
21072 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
21073 verbose pkgid bcrypt@0.8.5
21074 verbose cwd /tmp/deployment/application
21075 error Linux 3.14.48-33.39.amzn1.x86_64
21076 error argv "/opt/elasticbeanstalk/node-install/node-v0.12.6-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v0.12.6-linux-x64/bin/npm" "--production" "install"
21077 error node v0.12.6
21078 error npm  v2.11.2
21079 error code ELIFECYCLE
21080 error bcrypt@0.8.5 install: `node-gyp rebuild`
21080 error Exit status 1
21081 error Failed at the bcrypt@0.8.5 install script 'node-gyp rebuild'.
21081 error This is most likely a problem with the bcrypt package,
21081 error not with npm itself.
21081 error Tell the author that this fails on your system:
21081 error     node-gyp rebuild
21081 error You can get their info via:
21081 error     npm owner ls bcrypt
21081 error There is likely additional logging output above.
21082 verbose exit [ 1, true ]
21083 verbose unbuild node_modules/bcrypt
21084 info preuninstall bcrypt@0.8.5
21085 info uninstall bcrypt@0.8.5
21086 verbose unbuild rmStuff bcrypt@0.8.5 from /tmp/deployment/application/node_modules
21087 info postuninstall bcrypt@0.8.5
21088 silly gentlyRm /tmp/deployment/application/node_modules/bcrypt is being purged from base /tmp/deployment/application
21089 verbose gentlyRm don't care about contents; nuking /tmp/deployment/application/node_modules/bcrypt
21090 silly vacuum-fs purging /tmp/deployment/application/node_modules/bcrypt
21091 silly vacuum-fs quitting because other entries in /tmp/deployment/application/node_modules
```

A similar issue on another package: https://github.com/jedireza/drywall/issues/141
Unfortunately, the steps given did not help my case.

Judging from the requirements section, I shouldn't have to install any other librarires to build bcrypt since I am using v0.8.5.

Any ideas how to fix this?

Kindly,
Mathieu

**Comment by defunctzombie** [comment]
No idea. Likely some issue in beanstalk env or your environment. The log is not helpful.
