### ISSUE TITLE
bcrypt + node4.0 + windows

### ISSUE THREAD

**Issue by lslima91** [ncb000gt/node.bcrypt.js#341]
```

C:\Users\luis\Desktop\Scotch_Api\node_modules\bcrypt>if not defined npm_config_n
ode_gyp (node "C:\Users\luis\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-b
in\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild
)
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 status code downloading 64-bit node.lib
gyp ERR! stack     at Request.<anonymous> (C:\Users\luis\AppData\Roaming\npm\nod
e_modules\npm\node_modules\node-gyp\lib\install.js:403:20)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (C:\Users\luis\AppData\Roaming\n
pm\node_modules\npm\node_modules\request\request.js:985:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)

gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)

gyp ERR! stack     at Socket.socketOnData (_http_client.js:305:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\luis\\AppData
\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "re
build"
gyp ERR! cwd C:\Users\luis\Desktop\Scotch_Api\node_modules\bcrypt
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\luis\\AppData\\R
oaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "bcrypt"
npm ERR! node v4.0.0
npm ERR! npm  v2.13.0
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\luis\Desktop\Scotch_Api\npm-debug.log
```

**Comment by lslima91** [comment]
Known issue?

**Comment by nullivex** [comment]
@defunctzombie I am having this issue to, is there a fix?

**Comment by jferretiboke** [comment]
Read here: https://github.com/ncb000gt/node.bcrypt.js/issues/340.

**Comment by jferretiboke** [comment]
Try to install `node-gyp` with `$ npm install node-gyp -g` before to execute `node rebuild`. And if you get something like the next block, read https://github.com/ncb000gt/node.bcrypt.js/issues/340.

```
c:\xampp\htdocs\project\node_modules\bcrypt\build\bcrypt_lib.vcxproj(19,3): error MSB4019: No se encuentra el proyecto importado "c:\Microsoft.Cpp.Default.props". Asegúrese de que la ruta de acceso de la declaración <Import> es correcta y de que el archivo se encuentra en el disco.

gyp ERR! build error
gyp ERR! stack Error: C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\xampp\htdocs\projects\daatr-api\node_modules\bcrypt
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "bcrypt"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.5 install: 'node-gyp rebuild'
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.
```
