### ISSUE TITLE
error installing on OSX Yosemite

### ISSUE THREAD

**Issue by Gargamil** [ncb000gt/node.bcrypt.js#343]
Hi,

when i try to install it on OSX 10.10.5(Yosemite), it always give me this error:

```
 bcrypt@0.8.5 install /Users/Tobi/Documents/Code/node_modules/bcrypt
> node-gyp rebuild

  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
  SOLINK_MODULE(target) Release/bcrypt_lib.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/bcrypt_lib.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Tobi/Documents/Verlagshaus_Gruber/CRM-Erweiterung/Code/node_modules/bcrypt
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok 
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "bcrypt"
npm ERR! node v4.1.0
npm ERR! npm  v3.3.3
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.8.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!  /Users/Tobi/Documents/Code/npm-debug.log
```

I'm running node version node v4.1.0 and npm  v3.3.3

Help :(

edit:
I think the line "ld: library not found for -lgcc_s.10.5" is the problem.

**Comment by Gargamil** [comment]
temporary switched to bcryptjs

**Comment by voz** [comment]
@Gargamil creating symlinks for the libs as described [here](https://github.com/Homebrew/homebrew/issues/40653) solved the `ld: library not found for -lgcc_s.10.5` error for me:

```
$ cd /usr/local/lib
$ sudo ln -s ../../lib/libSystem.B.dylib libgcc_s.10.5.dylib
$ sudo ln -s ../../lib/libSystem.B.dylib libgcc_s.10.4.dylib
```

**Comment by defunctzombie** [comment]
make sure latest xcode and xcode command line tools are installed per the node-gyp requirements. I know this module works fine on yosemite so this is an issue with your system/environment setup.

**Comment by voz** [comment]
@defunctzombie FYI I'm on Yosemite 10.10.5 and have latest Xcode 6.3 and latest command line tools installed. But maybe indeed it's a problem with my environment.

**Comment by elwinbuisman** [comment]
@voz Life saver!

Had the same problem, I'm also on Yosemite 10.10.5 and have latest Xcode 6.3 and latest command line tools installed. Weird thing is, about 5 months ago I was able to install without any problems. Something changes somewhere apparently in my env. Even completely reinstalled node with no effect.

Anyways creating symlinks solved the issue!
