### ISSUE TITLE
Build Failing on node v4.1.0

### ISSUE THREAD

**Issue by michaelgilley** [ncb000gt/node.bcrypt.js#346]
When I install on node 4.1.0 (npm v2.14.5) I get the following:

```
> bcrypt@0.8.5 install /Users/michaelgilley/Sites/test/npmtests/node_modules/bcrypt
> node-gyp rebuild

  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
  SOLINK_MODULE(target) Release/bcrypt_lib.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/bcrypt_lib.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/michaelgilley/.nvm/versions/node/v4.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/Users/michaelgilley/.nvm/versions/node/v4.1.0/bin/node" "/Users/michaelgilley/.nvm/versions/node/v4.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/michaelgilley/Sites/test/npmtests/node_modules/bcrypt
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/michaelgilley/.nvm/versions/node/v4.1.0/bin/node" "/Users/michaelgilley/.nvm/versions/node/v4.1.0/bin/npm" "i" "-S" "bcrypt"
npm ERR! node v4.1.0
npm ERR! npm  v2.14.5
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.8.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.
```

**Comment by limianwang** [comment]
@defunctzombie Why did you close this? I'm having the _exact_ same issue on the mac. A little more information regarding this would be greatly helpful. This didn't happen before, and it isn't on Travis.

**Comment by defunctzombie** [comment]
Because an issue with this exact problem already exists and has notes on what to do about it.

**Comment by michaelgilley** [comment]
I apologize about this. For anyone looking for a SOLUTION to the `ld: library not found for -lgcc_s.10.5` issue: I realized (after some considerable time!!) that this was caused by upgrading Xcode to 6.4. I ended up uninstalling Xcode and reinstalling 7.0 from the App Store and that fixed it.
