### ISSUE TITLE
Cannot Install BCrypt

### ISSUE THREAD

**Issue by jylinman** [ncb000gt/node.bcrypt.js#348]
Hey guys,

I have been trying to install this bcrypt package but I am at a loss as I have tried many commands.  Could this be a bug?

I have tried these commands to get the right libraries and compilers:
```
sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer

npm i -g node-gyp && node-gyp clean

npm uninstall bcrypt && npm uninstall node-gyp && npm install node-gyp && npm install --save bcrypt

CC=/opt/local/bin/gcc CXX=/opt/local/bin/gcc npm install bcrypt

# Installed gcc48

# Went through https://github.com/ncb000gt/node.bcrypt.js/issues/90
```

Here is the output, let me know if you want the `npm-debug.log`

```
➜  api git:(master) ✗ npm install bcrypt --save

> fsevents@0.3.8 install /localhost/hugo/api/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/albanda/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/Users/albanda/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /localhost/hugo/api/node_modules/fsevents
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok
npm WARN install:fsevents fsevents@0.3.8 install: `node-gyp rebuild`
npm WARN install:fsevents Exit status 1

> bcrypt@0.8.5 install /localhost/hugo/api/node_modules/bcrypt
> node-gyp rebuild

  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
  SOLINK_MODULE(target) Release/bcrypt_lib.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/bcrypt_lib.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/albanda/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/Users/albanda/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /localhost/hugo/api/node_modules/bcrypt
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/Users/albanda/.nvm/versions/node/v0.12.7/bin/npm" "install" "bcrypt" "--save"
npm ERR! node v0.12.7
npm ERR! npm  v3.3.3
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /localhost/hugo/api/npm-debug.log
```

**Comment by jylinman** [comment]
Just saw the supported versions of node and I am running 0.12.7... Sorry about that guys.
