### ISSUE TITLE
Cannot get bcrypt to install node 4.1.1 npm 3.3.4

### ISSUE THREAD

**Issue by schme16** [ncb000gt/node.bcrypt.js#354]
I can't seem to get bcrypt to install ever since upgrading to 4.1.1, it just spits out the error below. Downgrading to 0.12.6 and installing works just fine, but dies as soon as I upgrade again.

Any ideas? I would really prefer to be running 4+

```sh
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed w
ith exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\U1038447\AppData\Roaming\npm\node_modu
les\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:1
2)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\U1038447\\AppData\\Roam
ing\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\U1038447\Dropbox\www\Work\2015\210-event-management-system\server\no
de_modules\bcrypt
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN EPACKAGEJSON eventy.xyz@0.0.0 No repository field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\U1038447\\AppData\\Roaming
\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "https://github.com/ncb000gt
/node.bcrypt.js.git"
npm ERR! node v4.1.1
npm ERR! npm  v3.3.4
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\U1038447\Dropbox\www\Work\2015\210-event-management-system\server\np
m-debug.log
```

**Comment by ashlinchak** [comment]
I have same issue. It seems the problem with node-gylp [GitHub](https://github.com/nodejs/node-gyp/issues/736)

**Comment by ashlinchak** [comment]
For some one who don't want to wait for update you should checkout your gcc and g++. It's should be 4.8. After update to these version I could install bcrypt.

**Comment by defunctzombie** [comment]
See that node gyp thread and make sure you have correct visual studio version.
