### ISSUE TITLE
npm install bcrypt fails on windows 32

### ISSUE THREAD

**Issue by s-a** [ncb000gt/node.bcrypt.js#361]
c:\git\electron-recompile>npm install bcrypt
    npm http GET https://registry.npmjs.org/bcrypt
    npm http 304 https://registry.npmjs.org/bcrypt
    npm http GET https://registry.npmjs.org/bindings/1.2.1
    npm http GET https://registry.npmjs.org/nan/2.0.5
    npm http 304 https://registry.npmjs.org/bindings/1.2.1
    npm http 304 https://registry.npmjs.org/nan/2.0.5
    > bcrypt@0.8.5 install c:\git\electron-recompile\node_modules\bcrypt
    > node-gyp rebuild
    c:\git\electron-recompile\node_modules\bcrypt>node "C:\Users\Stephan\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-    bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
    gyp http GET http://nodejs.org/dist/v4.2.1/node-v4.2.1.tar.gz
    gyp http 200 http://nodejs.org/dist/v4.2.1/node-v4.2.1.tar.gz
    gyp http GET http://nodejs.org/dist/v4.2.1/node.lib
    gyp http GET http://nodejs.org/dist/v4.2.1/x64/node.lib
    gyp http GET http://nodejs.org/dist/v4.2.1/x64/node.lib
    gyp http GET http://nodejs.org/dist/v4.2.1/node.lib
    gyp http 404 http://nodejs.org/dist/v4.2.1/x64/node.lib
    gyp WARN install got an error, rolling back install
    gyp http 404 http://nodejs.org/dist/v4.2.1/x64/node.lib
    gyp http 404 http://nodejs.org/dist/v4.2.1/node.lib
    gyp http 404 http://nodejs.org/dist/v4.2.1/node.lib
    gyp ERR! configure error
    gyp ERR! stack Error: 404 status code downloading 64-bit node.lib
    gyp ERR! stack     at Request.<anonymous> (C:\Users\Stephan\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\install.    js:313:20)
    gyp ERR! stack     at emitOne (events.js:82:20)
    gyp ERR! stack     at Request.emit (events.js:169:7)
    gyp ERR! stack     at Request.onResponse (C:\Users\Stephan\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.    js:816:10)
    gyp ERR! stack     at ClientRequest.g (events.js:260:16)
    gyp ERR! stack     at emitOne (events.js:77:13)
    gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
    gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)
    gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    gyp ERR! stack     at Socket.socketOnData (_http_client.js:305:20)
    gyp ERR! System Windows_NT 10.0.10240
    gyp ERR! command "C:\\Program Files\\nodejs\\node.exe"     "C:\\Users\\Stephan\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
    gyp ERR! cwd c:\git\electron-recompile\node_modules\bcrypt
    gyp ERR! node -v v4.2.1
    gyp ERR! node-gyp -v v0.12.1
    gyp ERR! not ok
    npm ERR! bcrypt@0.8.5 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the bcrypt@0.8.5 install script.
    npm ERR! This is most likely a problem with the bcrypt package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls bcrypt
    npm ERR! There is likely additional logging output above.
    npm ERR! System Windows_NT 10.0.10240
    npm ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Stephan\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.    js" "install" "bcrypt"
    npm ERR! cwd c:\git\electron-recompile
    npm ERR! node -v v4.2.1
    npm ERR! npm -v 1.3.17
    npm ERR! code ELIFECYCLE
    npm ERR!
    npm ERR! Additional logging details can be found in:
    npm ERR!     c:\git\electron-recompile\npm-debug.log
    npm ERR! not ok code 0

**Comment by s-a** [comment]
This seems to be a problem with node-gyp not brypt. Sorry
