### ISSUE TITLE
node-gyp rebuild fails on OS X 10.10.5

### ISSUE THREAD

**Issue by asbjornu** [ncb000gt/node.bcrypt.js#367]
When running `npm update` in [this particular fork of Drywall](/piratpartiet/drywall), it fails with the following exception:

```bash
> bcrypt@0.8.5 install /Users/bitbear/Dev.local/Drywall/node_modules/bcrypt
> node-gyp rebuild

  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
/Users/bitbear/Dev.local/Drywall/node_modules/.bin/touch: line 1: syntax error near unexpected token `('
/Users/bitbear/Dev.local/Drywall/node_modules/.bin/touch: line 1: `var touch = require("../touch")'
make: *** [Release/obj.target/bcrypt_lib/src/blowfish.o] Error 2
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/bitbear/Dev.local/Drywall/node_modules/bcrypt
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/bin/npm" "update"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.9
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.
```

I've read every comment in #90, but neither of the suggestions help. After removing `~/.node-gyp`, running this:

```bash
npm un bcrypt;npm i bcrypt --save;npm un node-gyp -g;npm i -g node-gyp && node-gyp clean
```

and everything else suggested there, `npm install` still fails. Any ideas what causes this and how I can fix it?

**Comment by vhtml** [comment]
mine is the same to you

**Comment by spdaly** [comment]
Same here.

**Comment by defunctzombie** [comment]
Not likely an issue with this module. Likely node-gyp issue if anything. Most likely an issue with your environment or setup.

**Comment by asbjornu** [comment]
@defunctzombie I don't know, but shouldn't an issue with my environment or setup cause a download of the latest bcrypt release and doing `npm install && make` fail? However, it succeeds:

```bash
> bcrypt@0.8.5 install /Users/bitbear/Downloads/node.bcrypt.js-0.8.5
> node-gyp rebuild

  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
  SOLINK_MODULE(target) Release/bcrypt_lib.node
node-gyp clean
gyp info it worked if it ends with ok
gyp info using node-gyp@3.0.3
gyp info using node@5.0.0 | darwin | x64
gyp info ok
node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@3.0.3
gyp info using node@5.0.0 | darwin | x64
gyp info spawn python2
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/bitbear/Downloads/node.bcrypt.js-0.8.5/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/bitbear/.node-gyp/5.0.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/bitbear/.node-gyp/5.0.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/bitbear/Downloads/node.bcrypt.js-0.8.5',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok
node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.0.3
gyp info using node@5.0.0 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
  SOLINK_MODULE(target) Release/bcrypt_lib.node
gyp info ok
npm install .

> bcrypt@0.8.5 install /Users/bitbear/Downloads/node.bcrypt.js-0.8.5
> node-gyp rebuild

  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
  SOLINK_MODULE(target) Release/bcrypt_lib.node

async.js
✔ test_salt_length
✔ test_salt_only_cb
✔ test_salt_rounds_is_string_number
✔ test_salt_rounds_is_string_non_number
✔ test_hash
✔ test_hash_rounds
✔ test_hash_empty_strings
✔ test_hash_no_params
✔ test_hash_one_param
✔ test_hash_salt_validity
✔ test_verify_salt
✔ test_verify_salt_min_rounds
✔ test_verify_salt_max_rounds
✔ test_hash_compare
✔ test_hash_compare_empty_strings
✔ test_hash_compare_invalid_strings

repetitions.js
✔ test_salt_length
✔ test_hash_length
✔ test_compare
✔ test_hash_and_compare

sync.js
✔ test_salt_length
✔ test_salt_no_params
✔ test_salt_rounds_is_string_number
✔ test_salt_rounds_is_NaN
✔ test_hash
✔ test_hash_rounds
✔ test_hash_empty_string
✔ test_hash_pw_no_params
✔ test_hash_pw_one_param
✔ test_hash_pw_not_hash_str
✔ test_hash_salt_validity
✔ test_verify_salt
✔ test_verify_salt_min_rounds
✔ test_verify_salt_max_rounds
✔ test_hash_compare
✔ test_hash_compare_empty_strings
✔ test_hash_compare_invalid_strings
✔ test_getRounds

OK: 15054 assertions (6170ms)
```

**Comment by asbjornu** [comment]
I also find it weird that `npm install bcrypt -g` works, while `npm install bcrypt` fails.

**Comment by asbjornu** [comment]
As I write in nodejs/node-gyp#795, I managed to solve the problem by installing the latest version of [touch](/isaacs/node-touch/releases):

```bash
npm install touch@latest
```

This allowed me to (first `unlink` and then) `npm install bcrypt` successfully. Seems like the version of touch I had installed was `0.0.4` and that the missing shebang that caused everything to crash has been added in version `1.0.0`.

**Comment by josiah14** [comment]
Ran into this problem trying to install ref on RHEL 6.5 with Node 0.10 (for an older project) and @asbjornu 's solution to install the latest version of "touch" worked for me as well.
