### ISSUE TITLE
Issues installing on Docker Image: 4.2.1-wheezy

### ISSUE THREAD

**Issue by mikeljames** [ncb000gt/node.bcrypt.js#368]
I'm getting this error (see below)
I had issues with this on travis ci, I had to specify the gcc version. https://github.com/travis-ci/travis-ci/issues/4771

Here Is my npm-shrinkwrap.json https://gist.github.com/mikeljames/6c3b617e2ae877082f4e

Any info will be helpful. Thanks :)

 in my docker container logs: 
``` 
/src/node_modules/bcrypt/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: /src/node_modules/bcrypt/build/Release/bcrypt_lib.node: invalid ELF header
    at Error (native)
    at Object.Module._extensions..node (module.js:460:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at bindings (/src/node_modules/bcrypt/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/src/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10) 
```

Docker Build Logs:
```
 > docker build -t wfh-api .
Sending build context to Docker daemon 31.72 MB
Step 0 : FROM node:4.2.1-wheezy
 ---> b7a1e9c01a4b
Step 1 : COPY . /src
 ---> e5a780f65265
Removing intermediate container 5ccb40608ecf
Step 2 : RUN cd /src; npm i
 ---> Running in bd8f8ee6f5af
npm info it worked if it ends with ok
npm info using npm@2.14.7
npm info using node@v4.2.1
npm info preinstall wfh-api@1.0.0
npm info package.json cradle@0.6.9 No repository field.
npm info package.json cradle@0.6.9 No license field.
npm info package.json getenv@0.5.0 No license field.
npm info package.json keymirror@0.1.1 No license field.
npm info package.json node-uuid@1.4.3 No license field.
npm info build /src
npm info linkStuff wfh-api@1.0.0
npm info build /src/node_modules/diskdb
npm info preinstall diskdb@0.1.14
npm info linkStuff diskdb@0.1.14
npm info install diskdb@0.1.14
npm info postinstall diskdb@0.1.14
npm info install wfh-api@1.0.0
npm info postinstall wfh-api@1.0.0
npm info prepublish wfh-api@1.0.0
npm info ok
 ---> dde088e4637a
Removing intermediate container bd8f8ee6f5af
Step 3 : ENV COUCHDB_USERNAME <username>
 ---> Running in 2e094691896e
 ---> ef9c20243336
Removing intermediate container 2e094691896e
Step 4 : ENV COUCHDB_PASSWORD <password>
 ---> Running in 059ce2d3f157
 ---> 9f436f17d84b
Removing intermediate container 059ce2d3f157
Step 5 : ENV COUCHDB_URL https://pebblecode.cloudant.com
 ---> Running in 4fbd72e345b8
 ---> 5716e73a28eb
Removing intermediate container 4fbd72e345b8
Step 6 : ENV COUCHDB_PORT 443
 ---> Running in 36ed9dece681
 ---> c37acb580ab3
Removing intermediate container 36ed9dece681
Step 7 : ENV COUCHDB_NAME pebblecode-wfh-dev
 ---> Running in aa2f8515b6e8
 ---> c12d9a4ebf69
Removing intermediate container aa2f8515b6e8
Step 8 : EXPOSE 3000
 ---> Running in 3883357bef90
 ---> 2dbec3dd91ea
Removing intermediate container 3883357bef90
Step 9 : CMD node /src/index.js
 ---> Running in f7bdab4ccc96
 ---> 12b3145ecc67
Removing intermediate container f7bdab4ccc96
Successfully built 12b3145ecc67
```

**Comment by mikeljames** [comment]
@defunctzombie  :( whats up? do you have a solution?

**Comment by defunctzombie** [comment]
It is probably an issue with your environment within the docker or maybe a node-gyp issue. It is not an issue with anything in this module.

**Comment by mikeljames** [comment]
yeah thats true, so I guess go and copy and paste this onto SO?
