### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by slopesidecreative** [ncb000gt/node.bcrypt.js#390]
OSX 10.10; Xcode 7.0; Command Line Tools; Python 2.7 and I cannot get it to install. Would really appreciate any assistance. I've checked permissions on ~/.npm and set to 775, but this doesnt seem like permissions. I've run the clear cache commands. Much thanks --

```
EriksMac:api Erik$ sudo npm install bcrypt@0.8.1
-
> bcrypt@0.8.1 install /apps/solutions/api/node_modules/bcrypt
> node-gyp rebuild

  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
In file included from ../src/bcrypt_node.cc:1:
In file included from ../node_modules/nan/nan.h:63:
../node_modules/nan/nan_new.h:207:43: error: inline declaration of 'NanNew' follows non-inline definition
template <typename T> inline v8::Local<T> NanNew(v8::Handle<T> h);
                                          ^
../node_modules/nan/nan_implementation_12_inl.h:218:1: note: previous definition is here
NanNew(v8::Handle<T> h) {
^
In file included from ../src/bcrypt_node.cc:1:
In file included from ../node_modules/nan/nan.h:63:
../node_modules/nan/nan_new.h:208:43: error: inline declaration of 'NanNew' follows non-inline definition
template <typename T> inline v8::Local<T> NanNew(v8::Persistent<T> const& p);
                                          ^
../node_modules/nan/nan_implementation_12_inl.h:224:1: note: previous definition is here
NanNew(v8::Persistent<T> const& p) {
^
2 errors generated.
make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1075:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /apps/solutions/api/node_modules/bcrypt
gyp ERR! node -v v0.12.9
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "bcrypt@0.8.1"
npm ERR! node v0.12.9
npm ERR! npm  v2.14.9
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
```

**Comment by slopesidecreative** [comment]
I tried 0.8.5 and it installed. That only took me a few hours to try. Shoot me now, please.
