### ISSUE TITLE
Module did not self-register

### ISSUE THREAD

**Issue by jichangfeng67** [ncb000gt/node.bcrypt.js#391]
### what I did before thing happen
It was working good, everything.

I delete the <code>node_module</code> repo for some reason

I modified some of my routes files, which has nothing with bcrypt

I <code>git rm, git add, git commit </code>several times

then I tried to <code>npm install</code> to get back the modules

I start the app by <code>npm start, node bin/www, pm2 start bin/www</code>, nothing worked.

here below is the error message:
```error
__base-repo__/node_modules/bcrypt/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (__base-repo__/node_modules/bcrypt/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (__base-repo__/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
npm ERR! weird error 1
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0

```
### and this is the package json
```json
{
  "name": "______",
  "version": "0.1.45",
  "private": true,
  "scripts": {
    "start": "node ./bin/www"
  },
  "dependencies": {
    "bcrypt": "~0.8.5",
    "body-parser": "^1.13.3",
    "cookie-parser": "~1.3.5",
    "debug": "~2.2.0",
    "express": "~4.13.1",
    "jade": "~1.11.0",
    "jsonwebtoken": "^5.4.1",
    "mongodb": "^2.0.49",
    "morgan": "~1.6.1",
    "serve-favicon": "~2.3.0",
    "twilio": "^2.8.0"
  }
}

```
anyone help!!!

**Comment by jichangfeng67** [comment]
Ohhh, found the solve method, it is because somehow I am using a legacy binary. I don't know what it is but after 
```
sudo apt-get install node-legacy
```
I am now using it properly!
Everything is fine now

**Comment by jichangfeng67** [comment]
Yeah, I solve the problem using apt-get install node-legacy, but this actions install a 0.10 version of node in my machine. So I can't use JS Promise any more. I want to use the 4.2.6 LTS version. Anyone know how to deal with it?

**Comment by ruffrey** [comment]
I think this goes here.

Running node@4.2.4 and npm@3.5.2, I can get it to build on ubuntu 14.04 with the following:

```
apt-get update -y
apt-get install -y software-properties-common
add-apt-repository ppa:ubuntu-toolchain-r/test
apt-get install -y python-software-properties
apt-get install -y gcc-4.8 g++-4.8
update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
```

But ultimately upon running the node app, it fails with this:

```
/usr/src/app/node_modules/bindings/bindings.js:83
     throw e
     ^

Error: /usr/src/app/node_modules/bcrypt/build/Release/bcrypt_lib.node: invalid ELF header
 at Error (native)
 at Object.Module._extensions..node (module.js:460:18)
 at Module.load (module.js:356:32)
 at Function.Module._load (module.js:313:12)
 at Module.require (module.js:366:17)
 at require (module.js:385:17)
 at bindings (/usr/src/app/node_modules/bindings/bindings.js:76:44)
 at Object.<anonymous> (/usr/src/app/node_modules/bcrypt/bcrypt.js:3:35)
 at Module._compile (module.js:435:26)
 at Module._extensions..js (module.js:442:10)
 at Object.require.extensions.(anonymous function) [as .js] (/usr/src/app/ode_modules/babel-register/lib/node.js:138:7)
 at Module.load (module.js:356:32)
 at Function.Module._load (module.js:313:12)
 at Module.require (module.js:366:17)
 at require (module.js:385:17)
 at Object.<anonymous> (/usr/src/app/lib/encrypt.js:7:15)
 at Module._compile (module.js:435:26)
 at loader (/usr/src/app/node_modules/babel-register/lib/node.js:130:5)
 at Object.require.extensions.(anonymous function) [as .js] (/usr/src/app/ode_modules/babel-register/lib/node.js:140:7)
 at Module.load (module.js:356:32)
 at Function.Module._load (module.js:313:12)
 at Module.require (module.js:366:17)
```

**Comment by jichangfeng67** [comment]
Thanks @ruffrey 
And I am sorry not being reply instantly, and actually I already solved the problem by 
`npm install npm -g` 
After you update the npm by the above line, you got the up-to-date version of NPM
and then
`sudo rm -r node-modules`
to remove all your packages(and if you clearly know which module is wrong, you may remove the specific ones)
and then
`npm install`
to reinstall all the packages.

###this is mainly because the lower version of npm caused the problem.
###the version of npm came with Nodejs.org official sites is usually lower than npm official version.
###So the first thing after you download the nodejs source and build it is:
##UPDATE ANYTHING

**Comment by ruffrey** [comment]
I appreciate the response. In the meantime I switched to bcrypt.js which seems good enough for now.

However, I'd gently suggest that a global module may not be the ideal solution. Good luck.

**Comment by ianwalter** [comment]
I'm running into this issue on macOS:
`Module did not self-register: '/Users/iwalter/ianwalter/nrg/node_modules/bcrypt/lib/binding/bcrypt_lib.node'`

```
Node v13.2.0
npm 6.13.1
```

I've run into this before but not sure *IF* or how I've resolved it in the past.
