### ISSUE TITLE
Issue installing on node 5.6.0

### ISSUE THREAD

**Issue by mavrick** [ncb000gt/node.bcrypt.js#398]
Windows 7 x64 with nodejs 5.6.0

```bash
C:\api> npm install bcrypt

> node-icu-charset-detector@0.1.4 install C:\api\node_modules\node-icu-charset-detector
> node-gyp rebuild


C:\api\node_modules\node-icu-charset-detector>if not defined npm_config_node_gyp (node "C:\P
rogram Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" r
ebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" s
witch.
  node-icu-charset-detector.cpp
..\node-icu-charset-detector.cpp(7): fatal error C1083: Cannot open include file: 'unicode/ucsdet.h'
: No such file or directory [C:\api\node_modules\node-icu-charset-detector\build\node-icu-c
harset-detector.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\
\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\api\node_modules\node-icu-charset-detector
gyp ERR! node -v v5.6.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
npm WARN install:node-icu-charset-detector@0.1.4 node-icu-charset-detector@0.1.4 install: `node-gyp r
ebuild`
npm WARN install:node-icu-charset-detector@0.1.4 Exit status 1
```

I have also added a comment here: https://github.com/mooz/node-icu-charset-detector/issues/27#issuecomment-187131159

**Comment by poliveira89** [comment]
How did you resolved this?
