### ISSUE TITLE
Unable to run module using node 6 on ubuntu 16.04

### ISSUE THREAD

**Issue by VMBindraban** [ncb000gt/node.bcrypt.js#419]
```
Error: Module version mismatch. Expected 46, got 48.
    at Error (native)
    at Object.Module._extensions..node (module.js:435:18)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at bindings (/home/vijay/Projects/nodejs/project/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/vijay/Projects/nodejs/project/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/vijay/Projects/nodejs/project/api/models/User.js:1:76)
    at Module._compile (module.js:410:26)
```
Node: 6.0 (with nvm)
NPM: 3.8.6
bcrypt: 0.8.6
OS: Ubuntu 16.04

I tried removing `node_modules` and `.npm` all together and flushing the npm cache but that didn't work.
Also tried npm rebuild.

Btw, i am getting `Error: Module version mismatch. Expected 46, got 47.` when using node 5.11
It works from node version 4.4.3.

**Comment by Redtear** [comment]
i have this error when user not a 6.x node version. When i use 6.x node version its all good.

**Comment by velocityzen** [comment]
same problem on os x 10.11.5

**Comment by defunctzombie** [comment]
rebuild

**Comment by goldfire** [comment]
I'm still seeing this on OS X 10.11 with node 6.2.0 and bcrypt 0.8.6. I tried deleting node_modules and running `npm rebuild`, but I still get `Error: Module version mismatch. Expected 46, got 48.`.

**Comment by VMBindraban** [comment]
Seems to work now, try `npm update`

**Comment by constantology** [comment]
I am having the same issue, I believe it's just the `nan` module dependency that needs to be updated to the latest version `~2.3.5`
