### ISSUE TITLE
Can't install on MacOS X

### ISSUE THREAD

**Issue by lennonjesus** [ncb000gt/node.bcrypt.js#424]
Hi.

I tried to install bcrypt package but I couldn't.

Command:
`npm install bcrypt --save --verbose
`

Versions:
```
node v5.11.1
npm  v3.8.6
nvm 0.31.1
```

Console output:
```
lennonjesus$ npm install bcrypt --save --verbose
npm info it worked if it ends with ok
npm verb cli [ '/Users/lennonjesus/.nvm/versions/node/v5.11.1/bin/node',
npm verb cli   '/Users/lennonjesus/.nvm/versions/node/v5.11.1/bin/npm',
npm verb cli   'install',
npm verb cli   'bcrypt',
npm verb cli   '--save',
npm verb cli   '--verbose' ]
npm info using npm@3.8.6
npm info using node@v5.11.1
npm verb request uri https://registry.npmjs.org/bcrypt
npm verb request no auth needed
npm info attempt registry request try #1 at 11:56:05 AM
npm verb request id 659127236ad37c7c
npm verb etag "A04SXZMPP6TAS3UL36OMDCLNL"
npm http request GET https://registry.npmjs.org/bcrypt
npm http 304 https://registry.npmjs.org/bcrypt
npm verb headers { date: 'Sun, 29 May 2016 14:56:06 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: '"A04SXZMPP6TAS3UL36OMDCLNL"',
npm verb headers   age: '0',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-iad2141-IAD',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '1',
npm verb headers   'x-timer': 'S1464533766.775498,VS0,VE390',
npm verb headers   vary: 'Accept-Encoding' }
npm verb etag https://registry.npmjs.org/bcrypt from cache
npm verb get saving bcrypt to /Users/lennonjesus/.npm/registry.npmjs.org/bcrypt/.cache.json
npm verb correctMkdir /Users/lennonjesus/.npm correctMkdir not in flight; initializing
npm verb cache add spec bcrypt
npm verb addNamed "latest" is being treated as a dist-tag for bcrypt
npm info addNameTag [ 'bcrypt', 'latest' ]
npm verb addNameTag registry:https://registry.npmjs.org/bcrypt not in flight; fetching
npm verb get https://registry.npmjs.org/bcrypt not expired, no request
npm verb addNamed "0.8.6" is a plain semver version for bcrypt
npm verb afterAdd /Users/lennonjesus/.npm/bcrypt/0.8.6/package/package.json not in flight; writing
npm verb correctMkdir /Users/lennonjesus/.npm correctMkdir not in flight; initializing
npm verb afterAdd /Users/lennonjesus/.npm/bcrypt/0.8.6/package/package.json written
npm verb request uri https://registry.npmjs.org/bindings
npm verb request no auth needed
npm info attempt registry request try #1 at 11:56:06 AM
npm verb etag "253W71VM8OY14XUCQXE1CJV6W"
npm http request GET https://registry.npmjs.org/bindings
npm verb request uri https://registry.npmjs.org/nan
npm verb request no auth needed
npm info attempt registry request try #1 at 11:56:06 AM
npm verb etag "24B26O57Z0ASCDVIYEYKA8KVW"
npm http request GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/bindings
npm verb headers { date: 'Sun, 29 May 2016 14:56:07 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: '"253W71VM8OY14XUCQXE1CJV6W"',
npm verb headers   age: '82',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-iad2141-IAD',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '3',
npm verb headers   'x-timer': 'S1464533767.983858,VS0,VE0',
npm verb headers   vary: 'Accept-Encoding' }
npm verb etag https://registry.npmjs.org/bindings from cache
npm verb get saving bindings to /Users/lennonjesus/.npm/registry.npmjs.org/bindings/.cache.json
npm verb correctMkdir /Users/lennonjesus/.npm correctMkdir not in flight; initializing
npm verb cache add spec bindings@1.2.1
npm verb addNamed "1.2.1" is a plain semver version for bindings
npm verb addNameVersion registry:https://registry.npmjs.org/bindings not in flight; fetching
npm verb get https://registry.npmjs.org/bindings not expired, no request
npm verb afterAdd /Users/lennonjesus/.npm/bindings/1.2.1/package/package.json not in flight; writing
npm verb correctMkdir /Users/lennonjesus/.npm correctMkdir not in flight; initializing
npm verb afterAdd /Users/lennonjesus/.npm/bindings/1.2.1/package/package.json written
npm http 304 https://registry.npmjs.org/nan
npm verb headers { date: 'Sun, 29 May 2016 14:56:08 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: '"24B26O57Z0ASCDVIYEYKA8KVW"',
npm verb headers   age: '254',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-iad2120-IAD',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '3',
npm verb headers   'x-timer': 'S1464533768.473204,VS0,VE0',
npm verb headers   vary: 'Accept-Encoding' }
npm verb etag https://registry.npmjs.org/nan from cache
npm verb get saving nan to /Users/lennonjesus/.npm/registry.npmjs.org/nan/.cache.json
npm verb correctMkdir /Users/lennonjesus/.npm correctMkdir not in flight; initializing
npm verb cache add spec nan@2.2.1
npm verb addNamed "2.2.1" is a plain semver version for nan
npm verb addNameVersion registry:https://registry.npmjs.org/nan not in flight; fetching
npm verb get https://registry.npmjs.org/nan not expired, no request
npm verb afterAdd /Users/lennonjesus/.npm/nan/2.2.1/package/package.json not in flight; writing
npm verb correctMkdir /Users/lennonjesus/.npm correctMkdir not in flight; initializing
npm verb afterAdd /Users/lennonjesus/.npm/nan/2.2.1/package/package.json written
npm verb correctMkdir /Users/lennonjesus/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /Users/lennonjesus/.npm/_locks/staging-080bc8163f6b3f58.lock for /Users/lennonjesus/Projects/myproject/myproject/myproject-api-2/node_modules/.staging
npm verb unbuild node_modules/.staging/nan-541c6ea5
npm verb unbuild node_modules/.staging/bindings-0822a41b
npm verb unbuild node_modules/.staging/bcrypt-369d993d
npm verb gentlyRm don't care about contents; nuking /Users/lennonjesus/Projects/myproject/myproject/myproject-api-2/node_modules/.staging/nan-541c6ea5
npm verb gentlyRm don't care about contents; nuking /Users/lennonjesus/Projects/myproject/myproject/myproject-api-2/node_modules/.staging/bindings-0822a41b
npm verb tar unpack /Users/lennonjesus/.npm/nan/2.2.1/package.tgz
npm verb tar unpacking to /Users/lennonjesus/Projects/myproject/myproject/myproject-api-2/node_modules/.staging/nan-541c6ea5
npm verb gentlyRm don't care about contents; nuking /Users/lennonjesus/Projects/myproject/myproject/myproject-api-2/node_modules/.staging/nan-541c6ea5
npm verb gentlyRm don't care about contents; nuking /Users/lennonjesus/Projects/myproject/myproject/myproject-api-2/node_modules/.staging/bcrypt-369d993d
npm verb tar unpack /Users/lennonjesus/.npm/bindings/1.2.1/package.tgz
npm verb tar unpacking to /Users/lennonjesus/Projects/myproject/myproject/myproject-api-2/node_modules/.staging/bindings-0822a41b
npm verb gentlyRm don't care about contents; nuking /Users/lennonjesus/Projects/myproject/myproject/myproject-api-2/node_modules/.staging/bindings-0822a41b
npm verb tar unpack /Users/lennonjesus/.npm/bcrypt/0.8.6/package.tgz
npm verb tar unpacking to /Users/lennonjesus/Projects/myproject/myproject/myproject-api-2/node_modules/.staging/bcrypt-369d993d
npm verb gentlyRm don't care about contents; nuking /Users/lennonjesus/Projects/myproject/myproject/myproject-api-2/node_modules/.staging/bcrypt-369d993d
npm verb gentlyRm don't care about contents; nuking /Users/lennonjesus/Projects/myproject/myproject/myproject-api-2/node_modules/.staging/bindings-0822a41b/node_modules
npm verb gentlyRm don't care about contents; nuking /Users/lennonjesus/Projects/myproject/myproject/myproject-api-2/node_modules/.staging/bcrypt-369d993d/node_modules
npm verb gentlyRm don't care about contents; nuking /Users/lennonjesus/Projects/myproject/myproject/myproject-api-2/node_modules/.staging/nan-541c6ea5/node_modules
npm info lifecycle nan@2.2.1~preinstall: nan@2.2.1
npm info lifecycle bindings@1.2.1~preinstall: bindings@1.2.1
npm info lifecycle bcrypt@0.8.6~preinstall: bcrypt@0.8.6
npm info linkStuff nan@2.2.1
npm verb linkBins nan@2.2.1
npm verb linkMans nan@2.2.1
npm info linkStuff bindings@1.2.1
npm verb linkBins bindings@1.2.1
npm verb linkMans bindings@1.2.1
npm info linkStuff bcrypt@0.8.6
npm verb linkBins bcrypt@0.8.6
npm verb linkMans bcrypt@0.8.6
npm info lifecycle nan@2.2.1~install: nan@2.2.1
npm info lifecycle bindings@1.2.1~install: bindings@1.2.1
npm info lifecycle bcrypt@0.8.6~install: bcrypt@0.8.6

> bcrypt@0.8.6 install /Users/lennonjesus/Projects/myproject/myproject/myproject-api-2/node_modules/bcrypt
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp verb cli [ '/Users/lennonjesus/.nvm/versions/node/v5.11.1/bin/node',
gyp verb cli   '/Users/lennonjesus/.nvm/versions/node/v5.11.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.3.1
gyp info using node@5.11.1 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at F (/Users/lennonjesus/.nvm/versions/node/v5.11.1/lib/node_modules/npm/node_modules/which/which.js:63:19)
gyp verb `which` failed     at E (/Users/lennonjesus/.nvm/versions/node/v5.11.1/lib/node_modules/npm/node_modules/which/which.js:72:29)
gyp verb `which` failed     at /Users/lennonjesus/.nvm/versions/node/v5.11.1/lib/node_modules/npm/node_modules/which/which.js:81:16
gyp verb `which` failed     at /Users/lennonjesus/.nvm/versions/node/v5.11.1/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
gyp verb `which` failed     at /Users/lennonjesus/.nvm/versions/node/v5.11.1/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:82:15)
gyp verb `which` failed  python2 [Error: not found: python2]
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /usr/bin/python
gyp verb check python version `/usr/bin/python -c "import platform; print(platform.python_version());"` returned: "2.7.10\n"
gyp verb get node dir no --target version specified, falling back to host node version: 5.11.1
gyp verb command install [ '5.11.1' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb install input version string "5.11.1"
gyp verb install installing version: 5.11.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 5.11.1
gyp verb build dir attempting to create "build" dir: /Users/lennonjesus/Projects/myproject/myproject/myproject-api-2/node_modules/bcrypt/build
gyp verb build dir "build" dir needed to be created? /Users/lennonjesus/Projects/myproject/myproject/myproject-api-2/node_modules/bcrypt/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /Users/lennonjesus/Projects/myproject/myproject/myproject-api-2/node_modules/bcrypt/build/config.gypi
gyp verb config.gypi checking for gypi file: /Users/lennonjesus/Projects/myproject/myproject/myproject-api-2/node_modules/bcrypt/config.gypi
gyp verb common.gypi checking for gypi file: /Users/lennonjesus/Projects/myproject/myproject/myproject-api-2/node_modules/bcrypt/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python
gyp info spawn args [ '/Users/lennonjesus/.nvm/versions/node/v5.11.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/lennonjesus/Projects/myproject/myproject/myproject-api-2/node_modules/bcrypt/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/lennonjesus/.nvm/versions/node/v5.11.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/lennonjesus/.node-gyp/5.11.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/lennonjesus/.node-gyp/5.11.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/lennonjesus/.nvm/versions/node/v5.11.1/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/lennonjesus/Projects/myproject/myproject/myproject-api-2/node_modules/bcrypt',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /Users/lennonjesus/.node-gyp/5.11.1
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
  c++ '-DNODE_GYP_MODULE_NAME=bcrypt_lib' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/Users/lennonjesus/.node-gyp/5.11.1/include/node -I/Users/lennonjesus/.node-gyp/5.11.1/src -I/Users/lennonjesus/.node-gyp/5.11.1/deps/uv/include -I/Users/lennonjesus/.node-gyp/5.11.1/deps/v8/include -I../node_modules/nan  -Os -gdwarf-2 -mmacosx-version-min=10.5 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++0x -fno-rtti -fno-exceptions -fno-threadsafe-statics -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/bcrypt_lib/src/blowfish.o.d.raw   -c -o Release/obj.target/bcrypt_lib/src/blowfish.o ../src/blowfish.cc
./Release/.deps/Release/obj.target/bcrypt_lib/src/blowfish.o.d.raw { dev: 16777218,
  mode: 33188,
  nlink: 1,
  uid: 501,
  gid: 20,
  rdev: 0,
  blksize: 4096,
  ino: 20450759,
  size: 87,
  blocks: 8,
  atime: Sun May 29 2016 11:56:10 GMT-0300 (BRT),
  mtime: Sun May 29 2016 11:56:10 GMT-0300 (BRT),
  ctime: Sun May 29 2016 11:56:10 GMT-0300 (BRT),
  birthtime: Sun May 29 2016 11:56:10 GMT-0300 (BRT) }
  c++ '-DNODE_GYP_MODULE_NAME=bcrypt_lib' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/Users/lennonjesus/.node-gyp/5.11.1/include/node -I/Users/lennonjesus/.node-gyp/5.11.1/src -I/Users/lennonjesus/.node-gyp/5.11.1/deps/uv/include -I/Users/lennonjesus/.node-gyp/5.11.1/deps/v8/include -I../node_modules/nan  -Os -gdwarf-2 -mmacosx-version-min=10.5 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++0x -fno-rtti -fno-exceptions -fno-threadsafe-statics -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/bcrypt_lib/src/bcrypt.o.d.raw   -c -o Release/obj.target/bcrypt_lib/src/bcrypt.o ../src/bcrypt.cc
./Release/.deps/Release/obj.target/bcrypt_lib/src/bcrypt.o.d.raw { dev: 16777218,
  mode: 33188,
  nlink: 1,
  uid: 501,
  gid: 20,
  rdev: 0,
  blksize: 4096,
  ino: 20450762,
  size: 83,
  blocks: 8,
  atime: Sun May 29 2016 11:56:10 GMT-0300 (BRT),
  mtime: Sun May 29 2016 11:56:10 GMT-0300 (BRT),
  ctime: Sun May 29 2016 11:56:10 GMT-0300 (BRT),
  birthtime: Sun May 29 2016 11:56:10 GMT-0300 (BRT) }
  c++ '-DNODE_GYP_MODULE_NAME=bcrypt_lib' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/Users/lennonjesus/.node-gyp/5.11.1/include/node -I/Users/lennonjesus/.node-gyp/5.11.1/src -I/Users/lennonjesus/.node-gyp/5.11.1/deps/uv/include -I/Users/lennonjesus/.node-gyp/5.11.1/deps/v8/include -I../node_modules/nan  -Os -gdwarf-2 -mmacosx-version-min=10.5 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++0x -fno-rtti -fno-exceptions -fno-threadsafe-statics -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/bcrypt_lib/src/bcrypt_node.o.d.raw   -c -o Release/obj.target/bcrypt_lib/src/bcrypt_node.o ../src/bcrypt_node.cc
./Release/.deps/Release/obj.target/bcrypt_lib/src/bcrypt_node.o.d.raw { dev: 16777218,
  mode: 33188,
  nlink: 1,
  uid: 501,
  gid: 20,
  rdev: 0,
  blksize: 4096,
  ino: 20450765,
  size: 1435,
  blocks: 8,
  atime: Sun May 29 2016 11:56:11 GMT-0300 (BRT),
  mtime: Sun May 29 2016 11:56:11 GMT-0300 (BRT),
  ctime: Sun May 29 2016 11:56:11 GMT-0300 (BRT),
  birthtime: Sun May 29 2016 11:56:11 GMT-0300 (BRT) }
  c++ -bundle -undefined dynamic_lookup -Wl,-search_paths_first -mmacosx-version-min=10.5 -arch x86_64 -L./Release  -o Release/bcrypt_lib.node Release/obj.target/bcrypt_lib/src/blowfish.o Release/obj.target/bcrypt_lib/src/bcrypt.o Release/obj.target/bcrypt_lib/src/bcrypt_node.o 
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/bcrypt_lib.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/lennonjesus/.nvm/versions/node/v5.11.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "/Users/lennonjesus/.nvm/versions/node/v5.11.1/bin/node" "/Users/lennonjesus/.nvm/versions/node/v5.11.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/lennonjesus/Projects/myproject/myproject/myproject-api-2/node_modules/bcrypt
gyp ERR! node -v v5.11.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm verb lifecycle bcrypt@0.8.6~install: unsafe-perm in lifecycle true
npm verb lifecycle bcrypt@0.8.6~install: PATH: /Users/lennonjesus/.nvm/versions/node/v5.11.1/lib/node_modules/npm/bin/node-gyp-bin:/Users/lennonjesus/Projects/myproject/myproject/myproject-api-2/node_modules/bcrypt/node_modules/.bin:/Users/lennonjesus/Projects/myproject/myproject/myproject-api-2/node_modules/.bin:/Users/lennonjesus/.nvm/versions/node/v5.11.1/bin:/Users/lennonjesus/.nvm/versions/node/v5.11.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin
npm verb lifecycle bcrypt@0.8.6~install: CWD: /Users/lennonjesus/Projects/myproject/myproject/myproject-api-2/node_modules/bcrypt
npm info lifecycle bcrypt@0.8.6~install: Failed to exec install script
npm verb unlock done using /Users/lennonjesus/.npm/_locks/staging-080bc8163f6b3f58.lock for /Users/lennonjesus/Projects/myproject/myproject/myproject-api-2/node_modules/.staging
npm verb stack Error: bcrypt@0.8.6 install: `node-gyp rebuild`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/Users/lennonjesus/.nvm/versions/node/v5.11.1/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
npm verb stack     at emitTwo (events.js:100:13)
npm verb stack     at EventEmitter.emit (events.js:185:7)
npm verb stack     at ChildProcess.<anonymous> (/Users/lennonjesus/.nvm/versions/node/v5.11.1/lib/node_modules/npm/lib/utils/spawn.js:24:14)
npm verb stack     at emitTwo (events.js:100:13)
npm verb stack     at ChildProcess.emit (events.js:185:7)
npm verb stack     at maybeClose (internal/child_process.js:850:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
npm verb pkgid bcrypt@0.8.6
npm verb cwd /Users/lennonjesus/Projects/myproject/myproject/myproject-api-2
npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/lennonjesus/.nvm/versions/node/v5.11.1/bin/node" "/Users/lennonjesus/.nvm/versions/node/v5.11.1/bin/npm" "install" "bcrypt" "--save" "--verbose"
npm ERR! node v5.11.1
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.8.6 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     npm-debug.log
```

[npm-debug.log](https://github.com/ncb000gt/node.bcrypt.js/files/288395/npm-debug.txt)

**Comment by defunctzombie** [comment]
```gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2```

**Comment by lennonjesus** [comment]
IMHO, the first message is just a warning (for now).

About python error, as you can see on log, the python executable has been found.

gyp verb `which` failed  python2 [Error: not found: python2]
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /usr/bin/python
gyp verb check python version `/usr/bin/python -c "import platform; print(platform.python_version());"` returned: "2.7.10\n"

**Comment by defunctzombie** [comment]
The real error seems to be `ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)`. This indicates your environment isn't setup correctly. Unfortunately there is not much to be done here on our end other than suggest you try to cleanup your environment and make it match the dependencies listed on the readme.

**Comment by lennonjesus** [comment]
I solved upgrading `Xcode`

from:
`version 6.3.1/Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)`

to:
`version 7.3.1/Apple LLVM version 7.3.0 (clang-703.0.31)`
