### ISSUE TITLE
Cannot run bcrypt with Node.js 6.2.1

### ISSUE THREAD

**Issue by hckhanh** [ncb000gt/node.bcrypt.js#426]
I receive this error when I upgrade from Node.js `5.11.1` to `6.2.1`:

```
Error: Module version mismatch. Expected 48, got 47.
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at bindings (C:\Users\hoang\projects\giveta-server\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (C:\Users\hoang\projects\giveta-server\node_modules\bcrypt\bcrypt.js:3:35)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\hoang\projects\giveta-server\models\user.js:6:16)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

I believe there is something wrong with bcrypt.

**Comment by hckhanh** [comment]
Finally, I figure out that I forget to rebuild my `node_modules`. So the version of module is mismatched.

```bash
npm rebuild
```
