### ISSUE TITLE
Module version mismatch. Expected 43, got 48.

### ISSUE THREAD

**Issue by ua2004** [ncb000gt/node.bcrypt.js#427]
I have the following:

    Node: 6.1.0
    NPM: 3.8.1
    Node-webkit: 0.12.3
    Windows 7 x64
    Visual Studio 2013

Here is my `authenticate` method:
```javascript
    authenticateSync: function(login, password) {
            var bcrypt = require('bcrypt');
            return User.findOne({where: {
               login: login,
            }}).then(function(user) {
               if(user === null) return false;
               return bcrypt.compareSync(password, user.password);
            });
         },
```
Console tests are working fine but whenever I run node-webkit I get this error:

    message: "Module version mismatch. Expected 43, got 48."
    stack: "Error: Module version mismatch. Expected 43, got 48.
    at Error (native)
    at Module.load (module.js:346:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:356:17)
    at require (module.js:375:17)
    at bindings (D:\Node\Project S\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (D:\Node\Project S\node_modules\bcrypt\bcrypt.js:3:35)
    at Module._compile (module.js:451:26
    at Object.Module._extensions..js (module.js:469:10)
    at Module.load (module.js:346:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:356:17)
    at require (module.js:375:17)
    at Object.<anonymous> (D:\Node\Project S\node_modules\bcrypt-as-promised\index.js:5:14)
    at Module._compile (module.js:451:26)
    at Object.Module._extensions..js (module.js:469:10)"

I tried to rebuild and recompile `bcrypt` module a couple of times but no luck.

**Comment by criticalboot** [comment]
facing same issue with
node: 6.1.0
electron: 1.2.1

Error: Module version mismatch. Expected 48, got 46.

**Comment by babsonmatt** [comment]
have you tried the following:
`./node_modules/.bin/electron-rebuild -v 1.2.1`

**Comment by goldfire** [comment]
I'm seeing the same thing without using either electron or nw.js.

**Comment by defunctzombie** [comment]
rebuild is the only recommended solution here. This happens when you built with one version of node but are trying to run with another

**Comment by nandarustam** [comment]
Hi @defunctzombie, I've tried everything everyone recommended and been urgently need this solved.
I've removed node_modules completely, clear cache, `npm install` and then `npm rebuild`, I tried all of them, but none of them worked.
My current version:
Node: 5.4.0
NPM: 3.3.12

I also have tried to update Node (6.2.2) and NPM (3.10.6) but still failing. So revert back to the previous.

These are the error I've been getting:

`Error: Module version mismatch. Expected 46, got 47.
     at Error (native)
     at Object.Module._extensions..node (module.js:460:18)
     at Module.load (module.js:356:32)
     at Function.Module._load (module.js:311:12)
     at Function.<anonymous> (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
     at Function.cls_wrapMethod (/home/dev/nodeapp/temanjalan-fire/node_modules/newrelic/lib/shimmer.js:246:38)
     at Function.Module._load (/home/dev/nodeapp/temanjalan-fire/node_modules/require-in-the-middle/index.js:22:24)
     at Module.require (module.js:366:17)
     at require (module.js:385:17)
     at bindings (/home/dev/nodeapp/temanjalan-fire/node_modules/bindings/bindings.js:76:44)
     at Object.<anonymous> (/home/dev/nodeapp/temanjalan-fire/node_modules/bcrypt/bcrypt.js:3:35)
     at Module._compile (module.js:435:26)
     at Object.Module._extensions..js (module.js:442:10)
     at Module.load (module.js:356:32)
     at Function.Module._load (module.js:311:12)
     at Function.<anonymous> (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
     at Function.cls_wrapMethod (/home/dev/nodeapp/temanjalan-fire/node_modules/newrelic/lib/shimmer.js:246:38)
     at Function.Module._load (/home/dev/nodeapp/temanjalan-fire/node_modules/require-in-the-middle/index.js:22:24)
     at Module.require (module.js:366:17)
     at require (module.js:385:17)
     at /home/dev/nodeapp/temanjalan-fire/models/User.js:11:17
     at Object.<anonymous> (/home/dev/nodeapp/temanjalan-fire/models/User.js:496:3)
     at Module._compile (module.js:435:26)
     at Object.Module._extensions..js (module.js:442:10)
     at Module.load (module.js:356:32)
     at Function.Module._load (module.js:311:12)
     at Function.<anonymous> (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
     at Function.cls_wrapMethod (/home/dev/nodeapp/temanjalan-fire/node_modules/newrelic/lib/shimmer.js:246:38)
     at Function.Module._load (/home/dev/nodeapp/temanjalan-fire/node_modules/require-in-the-middle/index.js:22:24)
     at Module.require (module.js:366:17)
     at require (module.js:385:17)
     at /home/dev/nodeapp/temanjalan-fire/services/auth.js:13:15
     at Object.<anonymous> (/home/dev/nodeapp/temanjalan-fire/services/auth.js:120:3)
     at Module._compile (module.js:435:26)
     at Object.Module._extensions..js (module.js:442:10)
     at Module.load (module.js:356:32)
     at Function.Module._load (module.js:311:12)
     at Function.<anonymous> (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
     at Function.cls_wrapMethod (/home/dev/nodeapp/temanjalan-fire/node_modules/newrelic/lib/shimmer.js:246:38)
     at Function.Module._load (/home/dev/nodeapp/temanjalan-fire/node_modules/require-in-the-middle/index.js:22:24)
     at Module.require (module.js:366:17)
     at require (module.js:385:17)
     at /home/dev/nodeapp/temanjalan-fire/server.js:29:15
     at Object.<anonymous> (/home/dev/nodeapp/temanjalan-fire/server.js:178:3)
     at Module._compile (module.js:435:26)
     at Object.Module._extensions..js (module.js:442:10)
     at Module.load (module.js:356:32)
     at Function.Module._load (module.js:311:12)
     at Function.<anonymous> (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
     at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js:28:21)
     at Module._compile (module.js:435:26)
     at Object.Module._extensions..js (module.js:442:10)
     at Module.load (module.js:356:32)
     at Function.Module._load (module.js:311:12)
     at Function.Module.runMain (module.js:467:10)
     at startup (node.js:136:18)
     at node.js:963:3`


Any help would be much appreciated

**Comment by defunctzombie** [comment]
Best thing I can recommend is to once again double check that you are building using the same version of node as your are trying to run with. Usually this happens if you run the build command in one terminal but then launch your app in another. Also make sure that there isn't some other version installed somewhere. By the looks of your stacktrace you have things installed in /usr/lib and stuff on /home/dev. This will lead to a bad time and I strongly recommend not installing stuff globally but instead keeping it locally to your apps/projects. npm works best this way.

**Comment by nandarustam** [comment]
Many thanks for the advice. I gave up and used another bcrypt module.
That was a one quick action needed to be done. But your advice will
definitely be useful someday, especially the part to keep all modules
locally. Many thanks anyway just for your response.

**Comment by ua2004** [comment]
Same for me, I used another bcrypt library written in pure JS: https://www.npmjs.com/package/bcrypt-nodejs

Works like a charm. However, I will take into account @defunctzombie's advice.
