### ISSUE TITLE
gyp ERR! stack Error: Python executable "python.EXE" is v3.5.1, which is not supported by gyp.

### ISSUE THREAD

**Issue by wzup** [ncb000gt/node.bcrypt.js#430]
How to bypass this error? I neither want to downgrade my Python version not to install any other versions.

```
$ npm install bcrypt --save

> bcrypt@0.8.7 install C:\Users\user\sbox\node\app\node_modules\bcrypt
> node-gyp rebuild


C:\Users\user\sbox\node\app\node_modules\bcrypt>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Python executable "C:\Users\user\AppData\Local\Programs\Python\Python35-32\python.EXE" is v3.5.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:406:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:395:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:193:7)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:850:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:323:11)
gyp ERR! stack     at emitOne (events.js:90:13)
gyp ERR! stack     at Socket.emit (events.js:182:7)
gyp ERR! stack     at Pipe._onclose (net.js:477:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\user\sbox\node\app\node_modules\bcrypt
gyp ERR! node -v v5.9.1
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@0.3.8
npm WARN less-loader@2.2.3 requires a peer of less@^2.3.1 but none was installed.
npm WARN material-ui@0.14.4 requires a peer of react@^0.14.0 but none was installed.
npm WARN material-ui@0.14.4 requires a peer of react-dom@^0.14.0 but none was installed.
npm WARN material-ui@0.14.4 requires a peer of react-tap-event-plugin@^0.2.0 but none was installed.
npm WARN react-addons-create-fragment@0.14.8 requires a peer of react@^0.14.8 but none was installed.
npm WARN react-addons-css-transition-group@15.0.2 requires a peer of react@^15.0.2 but none was installed.
npm WARN react-addons-pure-render-mixin@0.14.8 requires a peer of react@^0.14.8 but none was installed.
npm WARN react-addons-transition-group@0.14.8 requires a peer of react@^0.14.8 but none was installed.
npm WARN react-addons-update@0.14.8 requires a peer of react@^0.14.8 but none was installed.
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "bcrypt" "--save"
npm ERR! node v5.9.1
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\user\sbox\node\app\npm-debug.log
```

**Comment by wzup** [comment]
**UPD 1**

The package doesn't install even with Python 2.7.11

https://github.com/ncb000gt/node.bcrypt.js/issues/431
