### ISSUE TITLE
MSBUILD : error MSB4132: The tools version "2.0" is unrecognized. Available tools versions are "4.0".

### ISSUE THREAD

**Issue by wzup** [ncb000gt/node.bcrypt.js#431]
Ok, I've installed Python 2.7.11. But your package still doesn't install and throws errors. How to bypass this error now?

```
$ npm install --save bcrypt --python=C:\Python27

> bcrypt@0.8.7 install C:\Users\user\sbox\node\app\node_modules\bcrypt
> node-gyp rebuild


C:\Users\user\sbox\node\app\node_modules\bcrypt>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB4132: The tools version "2.0" is unrecognized. Available tools versions are "4.0".
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\user\sbox\node\app\node_modules\bcrypt
gyp ERR! node -v v5.9.1
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@0.3.8
npm WARN less-loader@2.2.3 requires a peer of less@^2.3.1 but none was installed.
npm WARN material-ui@0.14.4 requires a peer of react@^0.14.0 but none was installed.
npm WARN material-ui@0.14.4 requires a peer of react-dom@^0.14.0 but none was installed.
npm WARN material-ui@0.14.4 requires a peer of react-tap-event-plugin@^0.2.0 but none was installed.
npm WARN react-addons-create-fragment@0.14.8 requires a peer of react@^0.14.8 but none was installed.
npm WARN react-addons-css-transition-group@15.0.2 requires a peer of react@^15.0.2 but none was installed.
npm WARN react-addons-pure-render-mixin@0.14.8 requires a peer of react@^0.14.8 but none was installed.
npm WARN react-addons-transition-group@0.14.8 requires a peer of react@^0.14.8 but none was installed.
npm WARN react-addons-update@0.14.8 requires a peer of react@^0.14.8 but none was installed.
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "bcrypt" "--python=C:Python27"
npm ERR! node v5.9.1
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\user\sbox\node\app\npm-debug.log
```

**Comment by xTrot** [comment]
I was able fix this same problem by:
1. Installing the latest version of Python 2.7
2. Installing Visual Studio Community 2013
3. Running this command: npm config set msvs_version 2013

**Comment by wzup** [comment]
@xTrot 

What's the point to install whole huge Visual Studio just to get one build tool? MS offers all build tools as standalone downloads https://www.microsoft.com/en-in/download/details.aspx?id=48159
Can't we use just these build tools? Without visual studio?
