### ISSUE TITLE
install bcrypt with node 5.11.0 on linux

### ISSUE THREAD

**Issue by shuperry** [ncb000gt/node.bcrypt.js#433]
Here is my err:
```
[root@8 kingnoshop.com-api]# npm install bcrypt@0.8.6

> bcrypt@0.8.6 install /var/www/kingnoshop.com-api/node_modules/bcrypt
> node-gyp rebuild

make: Entering directory `/var/www/kingnoshop.com-api/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
cc1plus: 错误：无法识别的命令行选项“-std=gnu++0x”
make: *** [Release/obj.target/bcrypt_lib/src/blowfish.o] 错误 1
make: Leaving directory `/var/www/kingnoshop.com-api/node_modules/bcrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 2.6.18-371.el5xen
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/kingnoshop.com-api/node_modules/bcrypt
gyp ERR! node -v v5.11.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
kingnoshop.com-2.0-api@2.0.0 /var/www/kingnoshop.com-api
├── babel-register@6.9.0 
└── bindings@1.2.1  extraneous

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm ERR! Linux 2.6.18-371.el5xen
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "bcrypt@0.8.6"
npm ERR! node v5.11.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.8.6 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/kingnoshop.com-api/npm-debug.log
```

Help me, I am waitting, thks a lot.

**Comment by shuperry** [comment]
@defunctzombie You just close this without any words? Can you just advise me what I should do?

**Comment by defunctzombie** [comment]
Search through previous issues and follow up with folks that have encountered similar problem.
