### ISSUE TITLE
Can't install on OS X, lookup is done in C:/Python27/python.exe

### ISSUE THREAD

**Issue by timaschew** [ncb000gt/node.bcrypt.js#441]
```
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:/Python27/python.exe", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (/Users/awilhelm/n/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:401:14)
gyp ERR! stack     at /Users/awilhelm/n/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:330:11
gyp ERR! stack     at F (/Users/awilhelm/n/lib/node_modules/npm/node_modules/which/which.js:78:16)
gyp ERR! stack     at E (/Users/awilhelm/n/lib/node_modules/npm/node_modules/which/which.js:87:29)
gyp ERR! stack     at /Users/awilhelm/n/lib/node_modules/npm/node_modules/which/which.js:98:16
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "/Users/awilhelm/n/bin/node" "/Users/awilhelm/n/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/awilhelm/dev/deepstreamio/dsh-usermanagement/node_modules/bcrypt
gyp ERR! node -v v5.7.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok```
```

OS X 10.11.3

Python is installed (Python 2.7.11)

This helped:

`export PYTHON=/usr/local/bin/python`

**Comment by timaschew** [comment]
@defunctzombie 
From the readme it's not clear that I need to set this environment variable.
