### ISSUE TITLE
Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'

### ISSUE THREAD

**Issue by mroftalp** [ncb000gt/node.bcrypt.js#442]
I got an error after running `meteor npm install --save bcrypt`
```
> bcrypt@0.8.7 install /folder/to/meteor/app/node_modules/bcrypt
> node-gyp rebuild

  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
  SOLINK_MODULE(target) Release/bcrypt_lib.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/bcrypt_lib.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/folter/to/.meteor/packages/meteor-tool/.1.4.1.cbldeg++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/folder/to/.meteor/packages/meteor-tool/.1.4.1.cbldeg++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node" "/folder/to/.meteor/packages/meteor-tool/.1.4.1.cbldeg++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /folder/to/Meteor/client-portal-v2/node_modules/bcrypt
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Darwin 14.5.0
npm ERR! argv "/folder/to/.meteor/packages/meteor-tool/.1.4.1.cbldeg++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node" "/folder/to/.meteor/packages/meteor-tool/.1.4.1.cbldeg++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm" "install" "--save" "bcrypt"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.
```

**Comment by AnaCostache** [comment]
I have the same issue

**Comment by rickharrison** [comment]
Depending on your platform, you need to be able to run node-gyp with the instructions at: https://github.com/nodejs/node-gyp

**Comment by cvrabie** [comment]
Same thing seems to happen on aws after they updated to node v4.5.0

**Comment by mroftalp** [comment]
@rickharrison I installled node-gyp and also got another problem, it looks like it installled correctly, no error was shown, but when I type `node-gyp` in command lind it says the command is not found

**Comment by usman-ahmad** [comment]
I had similar issue when installing **accounts-password** package via `meteor add accounts-password`.

Successfully installed the package by first installing **npm-bcrypt** package via `meteor add npm-bcrypt` and then installing **accounts-password** package via `meteor add accounts-password`.

**Comment by bhirmbani** [comment]
i have the same exact issue like usman-ahmad and follow his step to install **accounts-password** package and it worked! Anyone can follow his step if you has the same problem. @usman-ahmad

**Comment by crdil** [comment]
I had the same issue on Arch Linux, I solved it by downgrading nodejs from 6.5.0 to 6.4.0

**Comment by defunctzombie** [comment]
Closing. There is nothing to fix in our repo for this. It is an environment config or setup issue. Hopefully your received the support needed here.

**Comment by miukki** [comment]
guys i have  seemlessly problem please answer 
```

me@me:~/Sites/winery$ meteor npm install --save bcrypt

> bcrypt@0.8.7 install /Users/miukki/Sites/winery/node_modules/bcrypt
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "/path/to/python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (/Users/miukki/.meteor/packages/meteor-tool/.1.4.1_1.16vitpk++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/node-gyp/lib/configure.js:449:14)
```

**Comment by miukki** [comment]
i have tried setup path to Pythong

`$ sudo vi /etc/launchd.conf
`


`setenv PYTHON /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
`

but it doesnt help any suggestion  ?

**Comment by miukki** [comment]
i installed gyp:

 `npm install -g node-gyp`

then did

`node-gyp rebuild`

and then faced other problem:

```
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: /Users/miukki/Sites/winery) while trying to load binding.gyp

```

**Comment by rickharrison** [comment]
This looks like it might be an issue with meteor. I encourage you to go to their support channels to ask them for help.

**Comment by brylie** [comment]
> This looks like it might be an issue with meteor.

@rickharrison what might the issue be? We would like to figure out how to resolve the problem.

**Comment by TechplexEngineer** [comment]
This fixed the issue for me `npm install -g node-gyp`

**Comment by shov** [comment]
there's no issue when I'm using node 8 but it is on node 11
