### ISSUE TITLE
npm install bcrypt failed

### ISSUE THREAD

**Issue by kimdotnet** [ncb000gt/node.bcrypt.js#447]
* What went wrong?
   npm install bcrypt --save failed
* What did you expect to happen?
   Successfully installed
* Which version of nodejs and OS?
```
   NodeJS 4.5.0
   Windows 10 64 bit
   Npm 3.10.7
```

Please see attachment file for further error message.
[npm-debug.txt](https://github.com/ncb000gt/node.bcrypt.js/files/484331/npm-debug.txt)

**Comment by okeydoke** [comment]
Yeah getting the same issue looks related to `node-gyp`

**Comment by jthomas124124** [comment]
Getting the same problem on MacOS Sierra (10.12) with NodeJS version 6.3.1 and NPM version 3.10.3

**Comment by defunctzombie** [comment]
No helpful error message in the log. Likely an issue with either your environment (make sure you have all the dependencies the readme lists) or some other temporary issue with npm (so try to clean and re-install).

Also it is helpful to just try installing this module by itself and eliminating the noise of the other modules you have installed.

**Comment by bholbrook73** [comment]
Getting the same issue on NPM v4.4.3. I cleared the npm cache and deleted the node modules folder and ran `npm install bcrypt`.

Results:
```
~/Projects/api-server $ npm install bcrypt
|
> bcrypt@0.8.6 install /home/bholbrook/Projects/api-server/node_modules/bcrypt
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory '/home/bholbrook/Projects/api-server/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
make: g++: Command not found
bcrypt_lib.target.mk:92: recipe for target 'Release/obj.target/bcrypt_lib/src/blowfish.o' failed
make: *** [Release/obj.target/bcrypt_lib/src/blowfish.o] Error 127
make: Leaving directory '/home/bholbrook/Projects/api-server/node_modules/bcrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/bholbrook/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-21-generic
gyp ERR! command "/home/bholbrook/.nvm/versions/node/v4.4.3/bin/node" "/home/bholbrook/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/bholbrook/Projects/api-server/node_modules/bcrypt
gyp ERR! node -v v4.4.3
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/home/bholbrook/.nvm/versions/node/v4.4.3/bin/node" "/home/bholbrook/.nvm/versions/node/v4.4.3/bin/npm" "install" "bcrypt"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.8.6 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bholbrook/Projects/api-server/npm-debug.log
```
