### ISSUE TITLE
Error thrown while attempting to install 

### ISSUE THREAD

**Issue by clnash** [ncb000gt/node.bcrypt.js#449]
Hi,

I'm brand new to this package. Im using it in conjunction with meteor.js. When I try to install the package, I get this error thrown:

```
`C:\Users\nash_\Documents\votingApp>meteor npm install --save bcrypt

> bcrypt@0.8.7 install C:\Users\nash_\Documents\votingApp\node_modules\bcrypt
> node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\nash_\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\python\python.exe", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Users\nash_\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Users\nash_\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Users\\nash_\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.1_1\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe" "C:\\Users\\nash_\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.1_1\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\nash_\Documents\votingApp\node_modules\bcrypt
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\nash_\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.1_1\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe" "C:\\Users\\nash_\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.1_1\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "bcrypt"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\nash_\Documents\votingApp\npm-debug.log

C:\Users\nash_\Documents\votingApp>meteor npm install --save bcrypt
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\nash_\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.1_1\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe" "C:\\Users\\nash_\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.1_1\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "bcrypt"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.6
npm ERR! file C:\Users\nash_\Documents\votingApp\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected end of input at 14:2
npm ERR!
npm ERR! ^
npm ERR! File: C:\Users\nash_\Documents\votingApp\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\nash_\Documents\votingApp\npm-debug.log
```
`I tried updating Node and NPM, and made sure that I have a compatible version of Python installed. 

Any suggestion into what I may be doing improperly?

Thank you
[npm-debug.zip](https://github.com/ncb000gt/node.bcrypt.js/files/497049/npm-debug.zip)

**Comment by defunctzombie** [comment]
Read the error above for suggestions on what to try.
